// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb556472737).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every interface, field, wire tag and switch arm below is derived from the
// Rust source. The prose is not; see tools/astgen/narrative.py.

// _base.ts — Pos, Node<T>, Comment, and the wire types they read.
// Mirrors `ast::Pos` / `NodeRef<T>` / `Comment` in `crates/ast/src/ast.rs`.

// --- Pos --------------------------------------------------------------

/**
 * `ast::Pos` — a tuple struct, so its five members are inlined into every
 * `NodeRef` on the wire rather than nested under a key of their own.
 * They are the same five keys in `Node`, which is why `Node` and `Comment`
 * extend `Partial<Pos>` instead of repeating the list.
 */
export interface Pos {
  filename: string;
  line: number;
  column: number;
  endLine: number;
  endColumn: number;
}

// --- Node -------------------------------------------------------------

/**
 * `Node<T>` — the positional wrapper around any AST payload.
 *
 * Rust's `ast::Node<T>` has a hand-written `Serialize` impl, so its output
 * keys come from that impl rather than from a derive. `id` is
 * `skip_deserializing` and only appears when the AST-index serialiser is
 * switched on, which is why it is optional and untyped: there is nothing to
 * decode it as, and guessing would be worse than passing it through.
 */
export interface Node<T> extends Partial<Pos> {
  node: T;
  id?: unknown;
}

/**
 * `NodeRef<T>` at both levels of optionality: the wrapper itself may be absent
 * (an `Option<NodeRef<T>>` field serializes as `null`), and a present wrapper
 * may still hold no value, since serde emits `"node": null` rather than
 * dropping the key. `Vec<Option<...>>` fields — `Arguments.defaults`,
 * `Arguments.ty_list` — are the same idea elementwise: the nulls are
 * meaningful and have to keep their slot.
 */
export type MaybeNode<T> = Node<T | undefined> | undefined;

// --- the wire shapes the helpers below take ---------------------------

/**
 * `NodeRef<T>` as it arrives: the payload under `node`, and the five
 * position members beside it. Every key is optional because `NodeRef` is
 * optional at *two* levels — the wrapper may be absent, and a wrapper that
 * is present may still hold no value.
 */
interface WireNode<U> {
  node: U;
  id?: unknown;
  filename?: string | undefined;
  line?: number | undefined;
  column?: number | undefined;
  end_line?: number | undefined;
  end_column?: number | undefined;
}

/**
 * The same five members without the payload, as a bare `Pos`. A `Pos` is a
 * tuple struct with no `Option` in it, so on the wire all five are
 * present together or the object is not a position at all -- unlike
 * `WireNode`, where they sit beside a payload that may itself be missing.
 */
interface WirePos {
  filename: string;
  line: number;
  column: number;
  end_line: number;
  end_column: number;
}

/**
 * Lift the five position members off a wrapper. Exported because `Pos`
 * is `ast.rs`'s own type and a caller holding a raw wire node should not have
 * to name the keys.
 */
export function posFromWire(w: WirePos | undefined | null): Pos | undefined {
  if (!w) return undefined;
  return {
    filename: w.filename,
    line: w.line,
    column: w.column,
    endLine: w.end_line,
    endColumn: w.end_column,
  };
}

/**
 * Decode one `NodeRef<T>`, given the loader for its payload. This is the
 * function every other decoder calls, and the reason a `NodeRef<T>` cannot
 * be a type on its own: the payload is polymorphic and the wrapper is not.
 */
export function nodeFromWire<T, U>(
  w: WireNode<U> | undefined | null,
  load: (inner: U) => T,
): Node<T> | undefined {
  if (!w) return undefined;
  const inner = w.node !== undefined ? load(w.node) : (undefined as unknown as T);
  return {
    node: inner,
    id: w.id,
    filename: w.filename,
    line: w.line,
    column: w.column,
    endLine: w.end_line,
    endColumn: w.end_column,
  };
}

/**
 * Decode a `Vec<T>` whose elements arrive bare -- no `NodeRef` wrapper around
 * any of them. `Target.paths : Vec<MemberOrIndex>` is the only such field in
 * the tree; every other list is `Vec<NodeRef<T>>` or
 * `Vec<Option<NodeRef<T>>>` and is read elementwise through `nodeFromWire`.
 * Sending this one through `nodeFromWire` instead reads a `node` key that is
 * not on the wire and yields a list of empty wrappers.
 *
 * The name is inherited from the hand-written binding and from the spelling
 * `hack/check_ast_field_types.rb` recognises for a list read; the return type
 * is `T[]`, not `Array<Node<T>>`.
 */
export function mapNodes<T>(
  items: unknown[] | undefined | null,
  load: (inner: never) => T,
): Array<T> {
  return (items || []).map((b) => load(b as never));
}

/**
 * `Comment` is a plain struct with one `String` field in Rust, so the object
 * under `node` is `{"text": "…"}` and not the text itself. Typing it as
 * `Node<string>` hands every caller an object where it promised a string.
 */
export interface Comment {
  text: string;
}

export function commentFromWire(
  w: { text?: string } | undefined | null,
): Comment | undefined {
  if (!w) return undefined;
  // `w` is the payload, not the wrapper. `Module.comments` reads this
  // through `nodeFromWire`, which lifts the `node` key off the
  // `NodeRef` before handing the element over, so the object `Comment`
  // is decoding is already `{"text": "…"}`. Unwrapping `node` a
  // second time reads a key that is not there and yields `''` for every
  // comment in the file without raising, which is why the round-trip
  // looks fine and the content does not.
  return {
    text: w.text ?? '',
  };
}
