// Code generated by tools/generate_ast.py from
// /Users/timi/codes/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every struct, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_go.py for the shapes and why they are so.

package ast

import (
	"encoding/json"
	"fmt"
)

// AssertStmt represents an assert statement, e.g. ```kcl assert True if
// condition, "Assert failed message" ```
type AssertStmt struct {
	Type   string    `json:"type,omitempty"`
	Test   *ExprNode `json:"test"`
	IfCond *ExprNode `json:"if_cond"`
	Msg    *ExprNode `json:"msg"`
}

// Read `AssertStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *AssertStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["test"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Test = c0
	}
	if raw, ok := d["if_cond"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.IfCond = c0
	}
	if raw, ok := d["msg"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Msg = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *AssertStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// AssignStmt represents an assignment, e.g. ```kcl a: int = 1 a["key"] =
// "value" a.b["key"].c = "value" a[0] = 1 ``` Valid left-hand side of an
// assignment expressions: - Expr::Identifier a - Expr::Subscript  e.g.
// `a[0]`, `b["k"]`
type AssignStmt struct {
	Type    string        `json:"type,omitempty"`
	Targets []*TargetNode `json:"targets"`
	Value   *ExprNode     `json:"value"`
	Ty      *TypeNode     `json:"ty"`
}

// Read `AssignStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *AssignStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["targets"]; ok && !isJSONNull(raw) {
		var c0 []*TargetNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Targets = c0
	}
	if raw, ok := d["value"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Value = c0
	}
	if raw, ok := d["ty"]; ok && !isJSONNull(raw) {
		var c0 *TypeNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Ty = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *AssignStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// AugAssignStmt represents an argument assignment, e.g. ```kcl a += 1 a[0] +=
// 2 ```
type AugAssignStmt struct {
	Type   string      `json:"type,omitempty"`
	Target *TargetNode `json:"target"`
	Value  *ExprNode   `json:"value"`
	Op     AugOp       `json:"op"`
}

// Read `AugAssignStmt` from its wire object. Every key is read through its
// own shape, which is the only place the four shapes can be told apart.
func (c *AugAssignStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["target"]; ok && !isJSONNull(raw) {
		var c0 *TargetNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Target = c0
	}
	if raw, ok := d["value"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Value = c0
	}
	if raw, ok := d["op"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.Op); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *AugAssignStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// ExprStmt represents a expression statement, e.g. ```kcl 1 """A long
// string""" ```
type ExprStmt struct {
	Type  string      `json:"type,omitempty"`
	Exprs []*ExprNode `json:"exprs"`
}

// Read `ExprStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *ExprStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["exprs"]; ok && !isJSONNull(raw) {
		var c0 []*ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Exprs = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *ExprStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// IfStmt, e.g. ```kcl if condition1: if condition2: a = 1 elif condition3: b
// = 2 else: c = 3 ```
type IfStmt struct {
	Type   string      `json:"type,omitempty"`
	Body   []*StmtNode `json:"body"`
	Cond   *ExprNode   `json:"cond"`
	Orelse []*StmtNode `json:"orelse"`
}

// Read `IfStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *IfStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["body"]; ok && !isJSONNull(raw) {
		var c0 []*StmtNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Body = c0
	}
	if raw, ok := d["cond"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Cond = c0
	}
	if raw, ok := d["orelse"]; ok && !isJSONNull(raw) {
		var c0 []*StmtNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Orelse = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *IfStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// ImportStmt, e.g. ```kcl import pkg as pkg_alias ```
type ImportStmt struct {
	Type    string      `json:"type,omitempty"`
	Path    *StringNode `json:"path"`
	Rawpath string      `json:"rawpath"`
	Name    string      `json:"name"`
	Asname  *StringNode `json:"asname"`
	PkgName string      `json:"pkg_name"`
}

// Read `ImportStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *ImportStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["path"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Path = c0
	}
	if raw, ok := d["rawpath"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.Rawpath); err != nil {
			return err
		}
	}
	if raw, ok := d["name"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.Name); err != nil {
			return err
		}
	}
	if raw, ok := d["asname"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Asname = c0
	}
	if raw, ok := d["pkg_name"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.PkgName); err != nil {
			return err
		}
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *ImportStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// RuleStmt, e.g. ```kcl rule RuleExample: a > 1 b < 0 ```
type RuleStmt struct {
	Type        string            `json:"type,omitempty"`
	Doc         *StringNode       `json:"doc"`
	Name        *StringNode       `json:"name"`
	ParentRules []*IdentifierNode `json:"parent_rules"`
	Decorators  []*CallExprNode   `json:"decorators"`
	Checks      []*CheckExprNode  `json:"checks"`
	Args        *ArgumentsNode    `json:"args"`
	ForHostName *IdentifierNode   `json:"for_host_name"`
}

// Read `RuleStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *RuleStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["doc"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Doc = c0
	}
	if raw, ok := d["name"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Name = c0
	}
	if raw, ok := d["parent_rules"]; ok && !isJSONNull(raw) {
		var c0 []*IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.ParentRules = c0
	}
	if raw, ok := d["decorators"]; ok && !isJSONNull(raw) {
		var c0 []*CallExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Decorators = c0
	}
	if raw, ok := d["checks"]; ok && !isJSONNull(raw) {
		var c0 []*CheckExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Checks = c0
	}
	if raw, ok := d["args"]; ok && !isJSONNull(raw) {
		var c0 *ArgumentsNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Args = c0
	}
	if raw, ok := d["for_host_name"]; ok && !isJSONNull(raw) {
		var c0 *IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.ForHostName = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *RuleStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// SchemaAttr, e.g. ```kcl schema SchemaAttrExample: x: int y: str ```
type SchemaAttr struct {
	Type       string          `json:"type,omitempty"`
	Doc        string          `json:"doc"`
	Name       *StringNode     `json:"name"`
	Op         *string         `json:"op"`
	Value      *ExprNode       `json:"value"`
	IsOptional bool            `json:"is_optional"`
	Decorators []*CallExprNode `json:"decorators"`
	Ty         *TypeNode       `json:"ty"`
}

// Read `SchemaAttr` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *SchemaAttr) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["doc"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.Doc); err != nil {
			return err
		}
	}
	if raw, ok := d["name"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Name = c0
	}
	c.Op = readOptString(d["op"])
	if raw, ok := d["value"]; ok && !isJSONNull(raw) {
		var c0 *ExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Value = c0
	}
	if raw, ok := d["is_optional"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.IsOptional); err != nil {
			return err
		}
	}
	if raw, ok := d["decorators"]; ok && !isJSONNull(raw) {
		var c0 []*CallExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Decorators = c0
	}
	if raw, ok := d["ty"]; ok && !isJSONNull(raw) {
		var c0 *TypeNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Ty = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *SchemaAttr) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// SchemaStmt, e.g. ```kcl schema BaseSchema:  schema
// SchemaExample(BaseSchema)[arg: str]: """Schema documents""" attr?: str =
// arg check: len(attr) > 3 if attr, "Check failed message"  mixin
// MixinExample for ProtocolExample: attr: int  protocol ProtocolExample:
// attr: int ```
type SchemaStmt struct {
	Type           string                    `json:"type,omitempty"`
	Doc            *StringNode               `json:"doc"`
	Name           *StringNode               `json:"name"`
	ParentName     *IdentifierNode           `json:"parent_name"`
	ForHostName    *IdentifierNode           `json:"for_host_name"`
	IsMixin        bool                      `json:"is_mixin"`
	IsProtocol     bool                      `json:"is_protocol"`
	Args           *ArgumentsNode            `json:"args"`
	Mixins         []*IdentifierNode         `json:"mixins"`
	Body           []*StmtNode               `json:"body"`
	Decorators     []*CallExprNode           `json:"decorators"`
	Checks         []*CheckExprNode          `json:"checks"`
	IndexSignature *SchemaIndexSignatureNode `json:"index_signature"`
}

// Read `SchemaStmt` from its wire object. Every key is read through its own
// shape, which is the only place the four shapes can be told apart.
func (c *SchemaStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["doc"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Doc = c0
	}
	if raw, ok := d["name"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Name = c0
	}
	if raw, ok := d["parent_name"]; ok && !isJSONNull(raw) {
		var c0 *IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.ParentName = c0
	}
	if raw, ok := d["for_host_name"]; ok && !isJSONNull(raw) {
		var c0 *IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.ForHostName = c0
	}
	if raw, ok := d["is_mixin"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.IsMixin); err != nil {
			return err
		}
	}
	if raw, ok := d["is_protocol"]; ok && !isJSONNull(raw) {
		if err := json.Unmarshal(raw, &c.IsProtocol); err != nil {
			return err
		}
	}
	if raw, ok := d["args"]; ok && !isJSONNull(raw) {
		var c0 *ArgumentsNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Args = c0
	}
	if raw, ok := d["mixins"]; ok && !isJSONNull(raw) {
		var c0 []*IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Mixins = c0
	}
	if raw, ok := d["body"]; ok && !isJSONNull(raw) {
		var c0 []*StmtNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Body = c0
	}
	if raw, ok := d["decorators"]; ok && !isJSONNull(raw) {
		var c0 []*CallExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Decorators = c0
	}
	if raw, ok := d["checks"]; ok && !isJSONNull(raw) {
		var c0 []*CheckExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Checks = c0
	}
	if raw, ok := d["index_signature"]; ok && !isJSONNull(raw) {
		var c0 *SchemaIndexSignatureNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.IndexSignature = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *SchemaStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// TypeAliasStmt represents a type alias statement, e.g. ```kcl type StrOrInt
// = str | int ```
type TypeAliasStmt struct {
	Type      string          `json:"type,omitempty"`
	TypeName  *IdentifierNode `json:"type_name"`
	TypeValue *StringNode     `json:"type_value"`
	Ty        *TypeNode       `json:"ty"`
}

// Read `TypeAliasStmt` from its wire object. Every key is read through its
// own shape, which is the only place the four shapes can be told apart.
func (c *TypeAliasStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["type_name"]; ok && !isJSONNull(raw) {
		var c0 *IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.TypeName = c0
	}
	if raw, ok := d["type_value"]; ok && !isJSONNull(raw) {
		var c0 *StringNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.TypeValue = c0
	}
	if raw, ok := d["ty"]; ok && !isJSONNull(raw) {
		var c0 *TypeNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Ty = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *TypeAliasStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// UnificationStmt represents a declare statement with the union operator,
// e.g. ```kcl data: ASchema {} ```
type UnificationStmt struct {
	Type   string          `json:"type,omitempty"`
	Target *IdentifierNode `json:"target"`
	Value  *SchemaExprNode `json:"value"`
}

// Read `UnificationStmt` from its wire object. Every key is read through its
// own shape, which is the only place the four shapes can be told apart.
func (c *UnificationStmt) fromWire(d map[string]json.RawMessage) error {
	if raw, ok := d["type"]; ok {
		if err := json.Unmarshal(raw, &c.Type); err != nil {
			return err
		}
	}
	if raw, ok := d["target"]; ok && !isJSONNull(raw) {
		var c0 *IdentifierNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Target = c0
	}
	if raw, ok := d["value"]; ok && !isJSONNull(raw) {
		var c0 *SchemaExprNode
		if err := json.Unmarshal(raw, &c0); err != nil {
			return err
		}
		c.Value = c0
	}
	return nil
}

// UnmarshalJSON is `fromWire` with the document already split. Every class
// gets one so a slot -- or any `json.Unmarshal` of a struct that holds one --
// reaches the same decoder the hierarchy dispatcher does.
func (c *UnificationStmt) UnmarshalJSON(b []byte) error {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return err
	}
	return c.fromWire(d)
}

// `Stmt` is one variant of the Stmt hierarchy. It is a marker interface
// rather than one with accessors: the classes are exported structs, so a
// caller type-switches on the concrete type, and Go has no equivalent of
// Python's `isinstance` over a generated variant table. The marker is
// unexported so the union cannot be implemented outside this package -- which
// is what makes the dispatcher's table exhaustive.
type Stmt interface {
	stmtNode()
}

// Read a `Stmt` off the wire. `type` is the discriminator every variant
// carries, so the dispatch is a lookup rather than a guess.
func stmtFromWire(raw json.RawMessage) (Stmt, error) {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(raw, &d); err != nil {
		return nil, err
	}
	var tag string
	if err := json.Unmarshal(d["type"], &tag); err != nil {
		return nil, err
	}
	switch tag {
	case "TypeAlias":
		var c TypeAliasStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Expr":
		var c ExprStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Unification":
		var c UnificationStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Assign":
		var c AssignStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "AugAssign":
		var c AugAssignStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Assert":
		var c AssertStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "If":
		var c IfStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Import":
		var c ImportStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "SchemaAttr":
		var c SchemaAttr
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Schema":
		var c SchemaStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	case "Rule":
		var c RuleStmt
		if err := c.fromWire(d); err != nil {
			return nil, err
		}
		return &c, nil
	}
	return nil, fmt.Errorf("unknown Stmt type: %s", tag)
}

// One line per variant: the unexported marker the interface needs, and a
// pointer receiver so the dispatcher can return the address it decoded into.
// Generated rather than written because a variant that is missing one is a
// compile error at the interface -- the compiler checks this part, and the
// field lists in the same file check the rest.
func (*TypeAliasStmt) stmtNode() {}

func (*ExprStmt) stmtNode() {}

func (*UnificationStmt) stmtNode() {}

func (*AssignStmt) stmtNode() {}

func (*AugAssignStmt) stmtNode() {}

func (*AssertStmt) stmtNode() {}

func (*IfStmt) stmtNode() {}

func (*ImportStmt) stmtNode() {}

func (*SchemaAttr) stmtNode() {}

func (*SchemaStmt) stmtNode() {}

func (*RuleStmt) stmtNode() {}
