//! ConsistencyTest — Zig counterpart of the Java
//! `java/src/test/java/com/kcl/ConsistencyTest.java`, the Go
//! `go/native/consistency_test.go` and the Python
//! `python/tests/consistency_test.py` runners.
//!
//! Executes the hermetic cases from `tests/consistency/cases.json` (the
//! manifest generated by `tests/consistency/generate_cases.py`) through the
//! native dispatcher and asserts the same golden expectations as every other
//! language runner. Nothing is hardcoded here: the case list, the arguments
//! and the expected values are all read from the shared manifest, so
//! regenerating the golden file turns a real language into a real red.
//!
//! Three steps, mirroring the reference runners:
//!
//! 1. parse the manifest and check `version == 1`;
//! 2. ask the loaded core for its RPC surface once per process via
//!    `BuiltinService.ListMethod`; a `new_core` case whose RPC is missing is
//!    skipped rather than failed, so the suite still runs on a stale core;
//! 3. dispatch on the `rpc` field and compare every field that actually
//!    appears in `expect`.
//!
//! Run with `zig build test` from the `zig` directory (the test binary links
//! the prebuilt `libkcl` like every other target in `build.zig`).

const std = @import("std");
const testing = std.testing;
const root = @import("root.zig");
const spec = @import("spec");
const test_options = @import("test_options");

const Value = std.json.Value;

/// Upper bound on the manifest size; the generated file is ~12 KiB.
const manifest_size_limit = 8 * 1024 * 1024;

/// The manifest version this runner understands.
const supported_manifest_version = 1;

/// Stand-in for an absent manifest node, so the accessors below stay total.
const absent: Value = .{ .null = {} };

const Case = struct {
    name: []const u8,
    rpc: []const u8,
    new_core: bool,
    args: Value,
    expect: Value,
};

/// Manifest, RPC surface and repository root, loaded once for the whole test
/// process (the reference runners cache the same three values in static
/// fields). The backing arena is intentionally not owned by
/// `testing.allocator`: a cached value cannot be freed between tests, and the
/// process exits right after the last one.
const Cache = struct {
    /// Kept alive so `cases` can borrow strings out of the parsed document.
    manifest: std.json.Parsed(Value),
    repo_root: []const u8,
    cases: []const Case,
    /// RPC names the loaded core advertises. Empty means "unknown surface",
    /// which the runners translate into skipping `new_core` cases.
    methods: std.StringHashMap(void),
};

/// Backing store for everything the manifest hands out. It is a global over
/// `std.heap.page_allocator` rather than a `testing.allocator` one because a
/// cached value cannot be freed between tests and the process exits right
/// after the last one. It must outlive `load`, so never store an
/// `std.mem.Allocator` taken from it — call `arena.allocator()` at each use
/// site, otherwise the cached `ptr` dangles the moment `load` returns.
var arena: std.heap.ArenaAllocator = .init(std.heap.page_allocator);
var cache: ?Cache = null;

/// Loads the manifest, resolves the repository root and probes the core's
/// RPC surface. Called once; every test then reuses the result.
fn load() !*Cache {
    if (cache) |*c| return c;
    const a = arena.allocator();

    const cases_path = test_options.consistency_cases;
    const raw = std.Io.Dir.cwd().readFileAlloc(testing.io, cases_path, a, .limited(manifest_size_limit)) catch |err| {
        std.debug.print(
            "consistency manifest not found at {s} ({s}). " ++
                "Run `python tests/consistency/generate_cases.py` to generate it.\n",
            .{ cases_path, @errorName(err) },
        );
        return err;
    };

    const manifest = std.json.parseFromSlice(Value, a, raw, .{}) catch |err| {
        std.debug.print("failed to parse {s}: {s}\n", .{ cases_path, @errorName(err) });
        return err;
    };

    const version: i64 = switch (field(manifest.value, "version") orelse absent) {
        .integer => |v| v,
        else => {
            std.debug.print("consistency manifest has no integer `version`\n", .{});
            return error.MissingManifestVersion;
        },
    };
    if (version != supported_manifest_version) {
        std.debug.print(
            "unsupported consistency manifest version: {d}\n",
            .{version},
        );
        return error.UnsupportedManifestVersion;
    }

    // The manifest pins `parse_args.paths` relative to the repository root,
    // which is the grandparent of the directory holding `cases.json`.
    const repo_root = repoRootOf(cases_path) orelse {
        std.debug.print("cannot derive the repository root from {s}\n", .{cases_path});
        return error.ManifestOutsideRepository;
    };

    const cases = try parseCases(a, manifest.value);
    const methods = try listMethods(a);

    cache = .{
        .manifest = manifest,
        .repo_root = repo_root,
        .cases = cases,
        .methods = methods,
    };
    return &cache.?;
}

/// Flattens `cases` into a slice so `findCase` can walk it by name.
fn parseCases(a: std.mem.Allocator, manifest: Value) ![]const Case {
    const raw = switch (field(manifest, "cases") orelse absent) {
        .array => |arr| arr.items,
        else => {
            std.debug.print("consistency manifest has no `cases` array\n", .{});
            return error.MissingCases;
        },
    };

    const cases = try a.alloc(Case, raw.len);
    for (raw, cases) |node, *case| {
        case.* = .{
            .name = text(node, "name"),
            .rpc = text(node, "rpc"),
            .new_core = boolean(node, "new_core"),
            .args = field(node, "args") orelse absent,
            .expect = field(node, "expect") orelse absent,
        };
        if (case.name.len == 0 or case.rpc.len == 0) {
            std.debug.print("consistency manifest holds a case without `name`/`rpc`\n", .{});
            return error.MalformedCase;
        }
    }
    return cases;
}

/// Asks the core which RPCs it implements, once per process. Cores predating
/// `BuiltinService.ListMethod` answer with an `ERROR:` payload (or otherwise
/// fail to decode), which surfaces here as an unknown surface rather than a
/// test failure — same as the `try/except` in the Java runner and the `err
/// != nil` branch of the Go one.
///
/// The reply is deliberately *not* deinitialised: it is owned by the cache
/// arena, and `ArenaAllocator.free` may rewind the arena end so that a later
/// allocation lands on the very bytes the map keys point at.
fn listMethods(a: std.mem.Allocator) !std.StringHashMap(void) {
    var methods: std.StringHashMap(void) = .init(a);
    const result = root.listMethod(a) catch |err| {
        std.debug.print(
            "note: the core could not list its RPC surface ({s}: {s}); `new_core` cases will be skipped\n",
            .{ @errorName(err), @typeName(root.Error) },
        );
        return methods;
    };
    for (result.method_name_list.items) |name| {
        try methods.put(name, {});
    }
    return methods;
}

// ---------------------------------------------------------------------------
// Manifest accessors. Optional keys read as the protobuf default so a case
// never depends on a field being present, matching the `path(...)` / `?? ...`
// handling of the Java and `a.get(...)` handling of the Python runner.
// ---------------------------------------------------------------------------

fn field(node: Value, key: []const u8) ?Value {
    return switch (node) {
        .object => |o| o.get(key),
        else => null,
    };
}

fn text(node: Value, key: []const u8) []const u8 {
    return switch (field(node, key) orelse return "") {
        .string => |s| s,
        else => "",
    };
}

fn boolean(node: Value, key: []const u8) bool {
    return switch (field(node, key) orelse return false) {
        .bool => |b| b,
        else => false,
    };
}

/// Appends `node[key]` as a list of strings, skipping absent keys and
/// non-string entries.
fn appendTexts(a: std.mem.Allocator, target: *std.ArrayList([]const u8), node: Value, key: []const u8) !void {
    switch (field(node, key) orelse return) {
        .array => |arr| for (arr.items) |item| switch (item) {
            .string => |s| try target.append(a, s),
            else => {},
        },
        else => {},
    }
}

/// Manifest path entries are pinned repo-relative by `generate_cases.py`;
/// absolute entries are kept as-is.
fn resolvePath(a: std.mem.Allocator, repo_root: []const u8, path: []const u8) ![]const u8 {
    if (std.fs.path.isAbsolute(path)) return path;
    return std.fs.path.join(a, &.{ repo_root, path });
}

/// `<root>/tests/consistency/cases.json` -> `<root>`. Three levels up from the
/// manifest file itself: the file, the `consistency` directory and `tests`.
fn repoRootOf(cases_path: []const u8) ?[]const u8 {
    var dir = cases_path;
    var levels: usize = 3;
    while (levels > 0) : (levels -= 1) {
        dir = std.fs.path.dirname(dir) orelse return null;
    }
    return dir;
}

// ---------------------------------------------------------------------------
// Request builders.
//
// These three functions populate messages whose string fields *borrow* from
// the parsed manifest, so they must be built with the cache arena and are
// never deinitialised: `protobuf.deinit` would try to free the borrowed
// bytes. Only the decoded results below are owned by the caller.
// ---------------------------------------------------------------------------

/// Builds the `ParseProgramArgs` of the schema-driven generation RPCs.
fn parseArgs(a: std.mem.Allocator, repo_root: []const u8, node: Value) !spec.ParseProgramArgs {
    var args: spec.ParseProgramArgs = .{};

    if (field(node, "paths")) |paths| switch (paths) {
        .array => |arr| for (arr.items) |item| switch (item) {
            .string => |p| try args.paths.append(a, try resolvePath(a, repo_root, p)),
            else => {},
        },
        else => {},
    };
    try appendTexts(a, &args.sources, node, "sources");
    // `external_pkgs` carries structured `ExternalPkg` messages rather than
    // strings, and the shared manifest leaves it empty; like the Java, Go and
    // Python runners this one only populates `paths` and `sources`.
    return args;
}

/// Builds the `ExecProgramArgs` of `KclService.ExecProgram` and
/// `KclService.GenerateToml`.
fn execArgs(a: std.mem.Allocator, node: Value) !spec.ExecProgramArgs {
    var args: spec.ExecProgramArgs = .{};
    try appendTexts(a, &args.k_code_list, node, "k_code_list");
    try appendTexts(a, &args.k_filename_list, node, "k_filename_list");
    try appendTexts(a, &args.overrides, node, "overrides");
    return args;
}

/// Builds the `TestResult` of `KclService.FormatTestReport`. The manifest
/// carries `duration` as a decimal string, matching the wire type (`uint64`)
/// without risking a float round-trip.
fn testResultArg(a: std.mem.Allocator, node: Value) !spec.TestResult {
    var result: spec.TestResult = .{};

    const info = field(node, "info") orelse return result;
    switch (info) {
        .array => |arr| for (arr.items) |entry| {
            const duration = try std.fmt.parseInt(u64, text(entry, "duration"), 10);
            try result.info.append(a, .{
                .name = text(entry, "name"),
                .@"error" = text(entry, "error"),
                .duration = duration,
                .log_message = text(entry, "log_message"),
            });
        },
        else => {},
    }
    return result;
}

// ---------------------------------------------------------------------------
// Expectation comparison
// ---------------------------------------------------------------------------

/// The value shapes the shared golden `expect` blocks use.
const Actual = union(enum) {
    text: []const u8,
    flag: bool,
};

const Observed = struct { name: []const u8, value: Actual };

/// Line-wise `--- expected / +++ actual` rendering, mirroring
/// `diffLines` in `go/native/consistency_test.go` so a golden mismatch reads
/// the same in every language.
fn diff(expected: []const u8, actual: []const u8, writer: *std.Io.Writer) !void {
    try writer.writeAll("--- expected\n+++ actual\n");
    var exp = std.mem.splitScalar(u8, expected, '\n');
    var act = std.mem.splitScalar(u8, actual, '\n');
    while (true) {
        const e = exp.next();
        const a = act.next();
        if (e == null and a == null) break;
        if (e != null and a != null and std.mem.eql(u8, e.?, a.?)) {
            try writer.print("  {s}\n", .{e.?});
        } else {
            if (e) |line| try writer.print("- {s}\n", .{line});
            if (a) |line| try writer.print("+ {s}\n", .{line});
        }
    }
}

/// Compares exactly the fields that appear in the case's `expect` block — the
/// field list is data, not code, so adding a golden field needs no runner
/// change while a golden change still turns this red.
fn expectFields(c: Case, observed: []const Observed) !void {
    var it = switch (c.expect) {
        .object => |o| o.iterator(),
        else => return error.MissingExpect,
    };
    while (it.next()) |entry| {
        const field_name = entry.key_ptr.*;
        const wanted = entry.value_ptr.*;
        var matched = false;
        for (observed) |o| {
            if (!std.mem.eql(u8, o.name, field_name)) continue;
            matched = true;
            switch (wanted) {
                .string => |want| {
                    if (o.value != .text) return error.FieldTypeMismatch;
                    if (std.mem.eql(u8, want, o.value.text)) continue;
                    var out: std.Io.Writer.Allocating = .init(testing.allocator);
                    defer out.deinit();
                    try diff(want, o.value.text, &out.writer);
                    std.debug.print(
                        "consistency case `{s}` field `{s}` mismatch:\n{s}",
                        .{ c.name, field_name, out.written() },
                    );
                    return error.ExpectMismatch;
                },
                .bool => |want| {
                    if (o.value != .flag) return error.FieldTypeMismatch;
                    try testing.expectEqual(want, o.value.flag);
                },
                else => return error.FieldTypeMismatch,
            }
        }
        // An `expect` key the RPC branch does not know about would otherwise
        // compare nothing and pass silently.
        if (!matched) {
            std.debug.print(
                "consistency case `{s}` expects field `{s}`, which the runner does not observe\n",
                .{ c.name, field_name },
            );
            return error.MissingObservedField;
        }
    }
}

/// The RPC surface the shared manifest exercises. Zig cannot switch on
/// strings, so the manifest's `rpc` field is mapped onto this tag once and
/// the dispatch below switches on it.
const Rpc = enum {
    ping,
    exec_program,
    format_code,
    validate_code,
    format_test_report,
    generate_toml,
    generate_kcl,
    generate_openapi,
    generate_proto,
    generate_doc,

    fn fromName(name: []const u8) ?Rpc {
        const table = .{
            .{ "KclService.Ping", Rpc.ping },
            .{ "KclService.ExecProgram", Rpc.exec_program },
            .{ "KclService.FormatCode", Rpc.format_code },
            .{ "KclService.ValidateCode", Rpc.validate_code },
            .{ "KclService.FormatTestReport", Rpc.format_test_report },
            .{ "KclService.GenerateToml", Rpc.generate_toml },
            .{ "KclService.GenerateKcl", Rpc.generate_kcl },
            .{ "KclService.GenerateOpenAPI", Rpc.generate_openapi },
            .{ "KclService.GenerateProto", Rpc.generate_proto },
            .{ "KclService.GenerateDoc", Rpc.generate_doc },
        };
        inline for (table) |entry| {
            if (std.mem.eql(u8, name, entry[0])) return entry[1];
        }
        return null;
    }
};

/// Looks a case up by name and reports a manifest that does not carry it.
fn findCase(c: *const Cache, name: []const u8) !*const Case {
    for (c.cases) |*case| {
        if (std.mem.eql(u8, case.name, name)) return case;
    }
    std.debug.print("consistency case not found in manifest: {s}\n", .{name});
    return error.UnknownCase;
}

/// Runs one named case: skips it when the core is too old for a `new_core`
/// RPC, otherwise dispatches on `rpc` and compares `expect`.
///
/// `a` owns the decoded results and must free them; the request messages are
/// built from the manifest arena (see the request-builder section) and live
/// for the whole process.
fn runCase(a: std.mem.Allocator, name: []const u8) !void {
    const c = try load();
    const case = try findCase(c, name);
    const args = arena.allocator();

    if (case.new_core and !c.methods.contains(case.rpc)) {
        std.debug.print(
            "skipping consistency case `{s}`: core does not list {s} (old core)\n",
            .{ case.name, case.rpc },
        );
        return;
    }

    const rpc = Rpc.fromName(case.rpc) orelse {
        std.debug.print("no runner support for rpc {s}\n", .{case.rpc});
        return error.UnsupportedRpc;
    };

    switch (rpc) {
        .ping => {
            var result = try root.ping(a, text(case.args, "value"));
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "value", .value = .{ .text = result.value } }});
        },
        .exec_program => {
            var result = try root.execProgram(a, try execArgs(args, case.args));
            defer result.deinit(a);
            try expectFields(case.*, &.{
                .{ .name = "yaml_result", .value = .{ .text = result.yaml_result } },
                .{ .name = "json_result", .value = .{ .text = result.json_result } },
            });
        },
        .format_code => {
            var result = try root.formatCode(a, .{ .source = text(case.args, "source") });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "formatted", .value = .{ .text = result.formatted } }});
        },
        .validate_code => {
            var result = try root.validateCode(a, .{
                .code = text(case.args, "code"),
                .data = text(case.args, "data"),
                .format = text(case.args, "format"),
            });
            defer result.deinit(a);
            try expectFields(case.*, &.{
                .{ .name = "success", .value = .{ .flag = result.success } },
                .{ .name = "err_message", .value = .{ .text = result.err_message } },
            });
        },
        .format_test_report => {
            const result_arg = try testResultArg(args, field(case.args, "result") orelse absent);
            var result = try root.formatTestReport(a, .{ .result = result_arg });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "report", .value = .{ .text = result.report } }});
        },
        .generate_toml => {
            const exec = try execArgs(args, field(case.args, "exec_args") orelse absent);
            var result = try root.generateToml(a, .{
                .exec_args = exec,
                .sort_keys = boolean(case.args, "sort_keys"),
            });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "toml", .value = .{ .text = result.toml } }});
        },
        .generate_kcl => {
            var result = try root.generateKcl(a, .{
                .source = text(case.args, "source"),
                .filename = text(case.args, "filename"),
                .format = text(case.args, "format"),
            });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "kcl", .value = .{ .text = result.kcl } }});
        },
        .generate_openapi => {
            const parse_arg = try parseArgs(args, c.repo_root, field(case.args, "parse_args") orelse absent);
            var result = try root.generateOpenAPI(a, .{
                .parse_args = parse_arg,
                .version = text(case.args, "version"),
            });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "spec", .value = .{ .text = result.spec } }});
        },
        .generate_proto => {
            const parse_arg = try parseArgs(args, c.repo_root, field(case.args, "parse_args") orelse absent);
            var result = try root.generateProto(a, .{
                .parse_args = parse_arg,
                .package = text(case.args, "package"),
            });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "proto", .value = .{ .text = result.proto } }});
        },
        .generate_doc => {
            const parse_arg = try parseArgs(args, c.repo_root, field(case.args, "parse_args") orelse absent);
            var result = try root.generateDoc(a, .{
                .parse_args = parse_arg,
                .format = text(case.args, "format"),
            });
            defer result.deinit(a);
            try expectFields(case.*, &.{.{ .name = "content", .value = .{ .text = result.content } }});
        },
    }
}

// ---------------------------------------------------------------------------
// One test per manifest case, so a failure names the case that broke (as the
// Java `@Test` methods and the Go `t.Run` subtests do).
// ---------------------------------------------------------------------------

test "consistency: the core advertises its RPC surface" {
    // Without this, a `listMethod` pointed at the wrong service degrades every
    // `new_core` case into a skip, and the whole runner goes quietly green.
    //
    // `KclService.ListMethod` is not an alias: a table naming it would mean the
    // wrapper regressed to the wrong service.
    //
    // `listMethods` allocates through the given allocator (the decode and the
    // hash map alike) and hands back no way to free the result, so hand it an
    // arena rather than `testing.allocator` and drop the whole thing at once.
    var arena_state = std.heap.ArenaAllocator.init(testing.allocator);
    defer arena_state.deinit();
    const methods = try listMethods(arena_state.allocator());
    try std.testing.expect(!methods.contains("KclService.ListMethod"));
    try std.testing.expect(methods.contains("KclService.ExecProgram"));
    try std.testing.expect(methods.contains("BuiltinService.ListMethod"));
    // Pin the registry size so a method cannot be dropped from the core
    // without this binding noticing -- `KclService.ListDepFiles` was removed
    // in v0.13.1, replaced by `LoadPackageResult.imports` / `kcl_mod` / `apps`.
    try std.testing.expectEqual(@as(usize, 28), methods.count());
}

test "consistency: ping" {
    try runCase(testing.allocator, "ping");
}

test "consistency: exec_program_basic" {
    try runCase(testing.allocator, "exec_program_basic");
}

test "consistency: exec_program_overrides" {
    try runCase(testing.allocator, "exec_program_overrides");
}

test "consistency: format_code" {
    try runCase(testing.allocator, "format_code");
}

test "consistency: validate_code_ok" {
    try runCase(testing.allocator, "validate_code_ok");
}

test "consistency: validate_code_invalid" {
    try runCase(testing.allocator, "validate_code_invalid");
}

test "consistency: generate_kcl_json" {
    try runCase(testing.allocator, "generate_kcl_json");
}

test "consistency: generate_kcl_yaml" {
    try runCase(testing.allocator, "generate_kcl_yaml");
}

test "consistency: generate_toml" {
    try runCase(testing.allocator, "generate_toml");
}

test "consistency: format_test_report" {
    try runCase(testing.allocator, "format_test_report");
}

test "consistency: generate_openapi_v3" {
    try runCase(testing.allocator, "generate_openapi_v3");
}

test "consistency: generate_proto" {
    try runCase(testing.allocator, "generate_proto");
}

test "consistency: generate_doc_md" {
    try runCase(testing.allocator, "generate_doc_md");
}
