<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message representing an application directory discovered under a package root.
 *
 * Generated from protobuf message <code>com.kcl.api.AppInfo</code>
 */
class AppInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Absolute path of the application directory.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * True when the directory contains a kcl.mod manifest.
     *
     * Generated from protobuf field <code>bool has_kcl_mod = 2;</code>
     */
    protected $has_kcl_mod = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Absolute path of the application directory.
     *     @type bool $has_kcl_mod
     *           True when the directory contains a kcl.mod manifest.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * Absolute path of the application directory.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Absolute path of the application directory.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * True when the directory contains a kcl.mod manifest.
     *
     * Generated from protobuf field <code>bool has_kcl_mod = 2;</code>
     * @return bool
     */
    public function getHasKclMod()
    {
        return $this->has_kcl_mod;
    }

    /**
     * True when the directory contains a kcl.mod manifest.
     *
     * Generated from protobuf field <code>bool has_kcl_mod = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setHasKclMod(bool $var)
    {
        $this->has_kcl_mod = $var;

        return $this;
    }

}

