<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for format file path response.
 *
 * Generated from protobuf message <code>com.kcl.api.FormatPathResult</code>
 */
class FormatPathResult extends \Google\Protobuf\Internal\Message
{
    /**
     * List of changed file paths.
     *
     * Generated from protobuf field <code>repeated string changed_paths = 1;</code>
     */
    private $changed_paths;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $changed_paths
     *           List of changed file paths.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * List of changed file paths.
     *
     * Generated from protobuf field <code>repeated string changed_paths = 1;</code>
     * @return RepeatedField<string>
     */
    public function getChangedPaths()
    {
        return $this->changed_paths;
    }

    /**
     * List of changed file paths.
     *
     * Generated from protobuf field <code>repeated string changed_paths = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setChangedPaths(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->changed_paths = $arr;

        return $this;
    }

}

