<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for generate TOML response.
 *
 * Generated from protobuf message <code>com.kcl.api.GenerateTomlResult</code>
 */
class GenerateTomlResult extends \Google\Protobuf\Internal\Message
{
    /**
     * The evaluated result serialized as TOML.
     *
     * Generated from protobuf field <code>string toml = 1;</code>
     */
    protected $toml = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $toml
     *           The evaluated result serialized as TOML.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * The evaluated result serialized as TOML.
     *
     * Generated from protobuf field <code>string toml = 1;</code>
     * @return string
     */
    public function getToml()
    {
        return $this->toml;
    }

    /**
     * The evaluated result serialized as TOML.
     *
     * Generated from protobuf field <code>string toml = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToml(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->toml = $var;

        return $this;
    }

}

