<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for generate KCL request arguments.
 *
 * Generated from protobuf message <code>com.kcl.api.GenerateKclArgs</code>
 */
class GenerateKclArgs extends \Google\Protobuf\Internal\Message
{
    /**
     * The source data content (JSON, YAML or TOML text).
     *
     * Generated from protobuf field <code>string source = 1;</code>
     */
    protected $source = '';
    /**
     * File name hint used for error messages and format detection, e.g. "data.json".
     *
     * Generated from protobuf field <code>string filename = 2;</code>
     */
    protected $filename = '';
    /**
     * Data format: "json", "yaml" or "toml". When empty, inferred from the
     * filename extension, defaulting to "json".
     *
     * Generated from protobuf field <code>string format = 3;</code>
     */
    protected $format = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $source
     *           The source data content (JSON, YAML or TOML text).
     *     @type string $filename
     *           File name hint used for error messages and format detection, e.g. "data.json".
     *     @type string $format
     *           Data format: "json", "yaml" or "toml". When empty, inferred from the
     *           filename extension, defaulting to "json".
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * The source data content (JSON, YAML or TOML text).
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @return string
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * The source data content (JSON, YAML or TOML text).
     *
     * Generated from protobuf field <code>string source = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSource(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->source = $var;

        return $this;
    }

    /**
     * File name hint used for error messages and format detection, e.g. "data.json".
     *
     * Generated from protobuf field <code>string filename = 2;</code>
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * File name hint used for error messages and format detection, e.g. "data.json".
     *
     * Generated from protobuf field <code>string filename = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFilename(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->filename = $var;

        return $this;
    }

    /**
     * Data format: "json", "yaml" or "toml". When empty, inferred from the
     * filename extension, defaulting to "json".
     *
     * Generated from protobuf field <code>string format = 3;</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Data format: "json", "yaml" or "toml". When empty, inferred from the
     * filename extension, defaulting to "json".
     *
     * Generated from protobuf field <code>string format = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setFormat(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->format = $var;

        return $this;
    }

}

