<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for get schema type mapping response.
 *
 * Generated from protobuf message <code>com.kcl.api.GetSchemaTypeMappingUnderPathResult</code>
 */
class GetSchemaTypeMappingUnderPathResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Map of pkg and schema types mappings.
     *
     * Generated from protobuf field <code>map<string, .com.kcl.api.SchemaTypes> schema_type_mapping = 1;</code>
     */
    private $schema_type_mapping;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $schema_type_mapping
     *           Map of pkg and schema types mappings.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * Map of pkg and schema types mappings.
     *
     * Generated from protobuf field <code>map<string, .com.kcl.api.SchemaTypes> schema_type_mapping = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSchemaTypeMapping()
    {
        return $this->schema_type_mapping;
    }

    /**
     * Map of pkg and schema types mappings.
     *
     * Generated from protobuf field <code>map<string, .com.kcl.api.SchemaTypes> schema_type_mapping = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSchemaTypeMapping(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Com\Kcl\Api\SchemaTypes::class);
        $this->schema_type_mapping = $arr;

        return $this;
    }

}

