<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for get schema type mapping request arguments.
 *
 * Generated from protobuf message <code>com.kcl.api.GetSchemaTypeMappingArgs</code>
 */
class GetSchemaTypeMappingArgs extends \Google\Protobuf\Internal\Message
{
    /**
     * Arguments for executing the program.
     *
     * Generated from protobuf field <code>.com.kcl.api.ExecProgramArgs exec_args = 1;</code>
     */
    protected $exec_args = null;
    /**
     * Name of the schema.
     *
     * Generated from protobuf field <code>string schema_name = 2;</code>
     */
    protected $schema_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Com\Kcl\Api\ExecProgramArgs $exec_args
     *           Arguments for executing the program.
     *     @type string $schema_name
     *           Name of the schema.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * Arguments for executing the program.
     *
     * Generated from protobuf field <code>.com.kcl.api.ExecProgramArgs exec_args = 1;</code>
     * @return \Com\Kcl\Api\ExecProgramArgs|null
     */
    public function getExecArgs()
    {
        return $this->exec_args;
    }

    public function hasExecArgs()
    {
        return isset($this->exec_args);
    }

    public function clearExecArgs()
    {
        unset($this->exec_args);
    }

    /**
     * Arguments for executing the program.
     *
     * Generated from protobuf field <code>.com.kcl.api.ExecProgramArgs exec_args = 1;</code>
     * @param \Com\Kcl\Api\ExecProgramArgs $var
     * @return $this
     */
    public function setExecArgs(\Com\Kcl\Api\ExecProgramArgs|null $var)
    {
        $this->exec_args = $var;

        return $this;
    }

    /**
     * Name of the schema.
     *
     * Generated from protobuf field <code>string schema_name = 2;</code>
     * @return string
     */
    public function getSchemaName()
    {
        return $this->schema_name;
    }

    /**
     * Name of the schema.
     *
     * Generated from protobuf field <code>string schema_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->schema_name = $var;

        return $this;
    }

}

