<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message representing an index signature in KCL.
 *
 * Generated from protobuf message <code>com.kcl.api.IndexSignature</code>
 */
class IndexSignature extends \Google\Protobuf\Internal\Message
{
    /**
     * The optional index signature key name
     *
     * Generated from protobuf field <code>optional string key_name = 1;</code>
     */
    protected $key_name = null;
    /**
     * Key type of the index signature.
     *
     * Generated from protobuf field <code>.com.kcl.api.KclType key = 2;</code>
     */
    protected $key = null;
    /**
     * Value type of the index signature.
     *
     * Generated from protobuf field <code>.com.kcl.api.KclType val = 3;</code>
     */
    protected $val = null;
    /**
     * Generated from protobuf field <code>bool any_other = 4;</code>
     */
    protected $any_other = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key_name
     *           The optional index signature key name
     *     @type \Com\Kcl\Api\KclType $key
     *           Key type of the index signature.
     *     @type \Com\Kcl\Api\KclType $val
     *           Value type of the index signature.
     *     @type bool $any_other
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * The optional index signature key name
     *
     * Generated from protobuf field <code>optional string key_name = 1;</code>
     * @return string
     */
    public function getKeyName()
    {
        return isset($this->key_name) ? $this->key_name : '';
    }

    public function hasKeyName()
    {
        return isset($this->key_name);
    }

    public function clearKeyName()
    {
        unset($this->key_name);
    }

    /**
     * The optional index signature key name
     *
     * Generated from protobuf field <code>optional string key_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKeyName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->key_name = $var;

        return $this;
    }

    /**
     * Key type of the index signature.
     *
     * Generated from protobuf field <code>.com.kcl.api.KclType key = 2;</code>
     * @return \Com\Kcl\Api\KclType|null
     */
    public function getKey()
    {
        return $this->key;
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * Key type of the index signature.
     *
     * Generated from protobuf field <code>.com.kcl.api.KclType key = 2;</code>
     * @param \Com\Kcl\Api\KclType $var
     * @return $this
     */
    public function setKey(\Com\Kcl\Api\KclType|null $var)
    {
        $this->key = $var;

        return $this;
    }

    /**
     * Value type of the index signature.
     *
     * Generated from protobuf field <code>.com.kcl.api.KclType val = 3;</code>
     * @return \Com\Kcl\Api\KclType|null
     */
    public function getVal()
    {
        return $this->val;
    }

    public function hasVal()
    {
        return isset($this->val);
    }

    public function clearVal()
    {
        unset($this->val);
    }

    /**
     * Value type of the index signature.
     *
     * Generated from protobuf field <code>.com.kcl.api.KclType val = 3;</code>
     * @param \Com\Kcl\Api\KclType $var
     * @return $this
     */
    public function setVal(\Com\Kcl\Api\KclType|null $var)
    {
        $this->val = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool any_other = 4;</code>
     * @return bool
     */
    public function getAnyOther()
    {
        return $this->any_other;
    }

    /**
     * Generated from protobuf field <code>bool any_other = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAnyOther(bool $var)
    {
        $this->any_other = $var;

        return $this;
    }

}

