<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for rename code response.
 *
 * Generated from protobuf message <code>com.kcl.api.RenameCodeResult</code>
 */
class RenameCodeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Map of changed code with filename as key and modified code as value.
     *
     * Generated from protobuf field <code>map<string, string> changed_codes = 1;</code>
     */
    private $changed_codes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $changed_codes
     *           Map of changed code with filename as key and modified code as value.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * Map of changed code with filename as key and modified code as value.
     *
     * Generated from protobuf field <code>map<string, string> changed_codes = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getChangedCodes()
    {
        return $this->changed_codes;
    }

    /**
     * Map of changed code with filename as key and modified code as value.
     *
     * Generated from protobuf field <code>map<string, string> changed_codes = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setChangedCodes(array|\Google\Protobuf\Internal\MapField $var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->changed_codes = $arr;

        return $this;
    }

}

