<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spec.proto

namespace Com\Kcl\Api;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Message for validate code response.
 *
 * Generated from protobuf message <code>com.kcl.api.ValidateCodeResult</code>
 */
class ValidateCodeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Flag indicating if validation was successful.
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     */
    protected $success = false;
    /**
     * Error message from validation.
     *
     * Generated from protobuf field <code>string err_message = 2;</code>
     */
    protected $err_message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $success
     *           Flag indicating if validation was successful.
     *     @type string $err_message
     *           Error message from validation.
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\Spec::initOnce();
        parent::__construct($data);
    }

    /**
     * Flag indicating if validation was successful.
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Flag indicating if validation was successful.
     *
     * Generated from protobuf field <code>bool success = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setSuccess(bool $var)
    {
        $this->success = $var;

        return $this;
    }

    /**
     * Error message from validation.
     *
     * Generated from protobuf field <code>string err_message = 2;</code>
     * @return string
     */
    public function getErrMessage()
    {
        return $this->err_message;
    }

    /**
     * Error message from validation.
     *
     * Generated from protobuf field <code>string err_message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->err_message = $var;

        return $this;
    }

}

