# Code generated by tools/generate_ast.py from
# kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb556472737).
# DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
# result, or `ruby hack/check_generated_ast.rb` will fail.
#
# Every class, field, wire tag and operator below is derived from the Rust
# source. The prose is not; see tools/astgen/narrative.py.

"""Typed AST package for the KCL Python binding.

The AST JSON wire format is whatever the Rust compiler in
``kcl-lang/kcl/crates/ast/src/ast.rs`` emits via ``serde_json``. This package
mirrors that shape as Python dataclasses so Python callers can consume the
``ast_json`` field returned by ``api.parse_file`` / ``api.parse_program`` as
typed objects rather than raw ``dict``s::

    from kcl_lib.ast import Module, SchemaStmt, parse_module
    module = parse_module(api.parse_file(args).ast_json)

Three wire shapes, and picking the wrong one fails silently rather than
loudly — the whole point of the contract tests in
``python/tests/ast_contract_test.py`` is to catch that:

* ``Stmt`` and ``Expr`` are ``#[serde(tag = "type")]`` with no
  ``rename_all``. The tag is the Rust *variant name* verbatim — ``NumberLit``,
  ``StringLit``, ``Check``, not the ``get_expr_name()`` diagnostic spelling
  (``"CheckExpression"``) and not the ``Literal``-enum short form
  (``"Number"``). The variant's struct fields are flattened into the same
  object, so ``{"type":"Identifier","names":[...]}`` has no wrapper key.
* ``Type`` is ``#[serde(tag = "type", content = "value")]`` — adjacently
  tagged, and the tag names the *shape*: ``{"type":"Basic","value":"Int"}``.
* Everything else (``Identifier``, ``Target``, ``Keyword``, ``Arguments``,
  ``ConfigEntry``, ``CheckExpr``, ``CallExpr``, ``CompClause``, …) is a plain
  struct with no tag at all.

A decorator is a ``CallExpr`` and ``UnificationStmt.value`` is a
``SchemaExpr``; both reach the same struct through a field declared with the
struct rather than the enum variant, which is why the tag is missing there.
``Decorator`` and ``SchemaConfig`` are exported as aliases documenting that.

Every module in this package is generated by ``tools/generate_ast.py`` from
``crates/ast/src/ast.rs``. Do not edit any of them by hand — run the generator
and commit the result."""

from ._base import (
    Comment,
    Node,
    Pos,
    node_from_dict,
    node_list_from_dict,
    node_to_dict,
    optional_node_list_from_dict,
    optional_node_list_to_dict,
    parse_module,
    parse_program,
)
from ._op import (
    AugOp,
    BinOp,
    CmpOp,
    ConfigEntryOperation,
    NumberBinarySuffix,
    QuantOperation,
    UnaryOp,
)
from ._dto import (
    Arguments,
    CallExpr,
    CheckExpr,
    CompClause,
    ConfigEntry,
    Decorator,
    Identifier,
    IdentifierExpr,
    IntLiteralType,
    KeyValuePair,
    Keyword,
    MemberOrIndex,
    SchemaConfig,
    SchemaExpr,
    SchemaIndexSignature,
    Target,
    TargetExpr,
)
from ._expr import (
    BinaryExpr,
    Compare,
    ConfigExpr,
    ConfigIfEntryExpr,
    DictComp,
    Expr,
    ExprContext,
    FormattedValue,
    IfExpr,
    JoinedString,
    LambdaExpr,
    ListComp,
    ListExpr,
    ListIfItemExpr,
    MissingExpr,
    NameConstantLit,
    NumberLit,
    NumberLitValue,
    ParenExpr,
    QuantExpr,
    SelectorExpr,
    StarredExpr,
    StringLit,
    Subscript,
    UnaryExpr,
    UnknownExpr,
    expr_from_dict,
    expr_to_dict,
)
from ._stmt import (
    AssertStmt,
    AssignStmt,
    AugAssignStmt,
    ExprStmt,
    IfStmt,
    ImportStmt,
    RuleStmt,
    SchemaAttr,
    SchemaStmt,
    Stmt,
    TypeAliasStmt,
    UnificationStmt,
    UnknownStmt,
    stmt_from_dict,
    stmt_to_dict,
)
from ._types import (
    AnyType,
    BasicType,
    DictType,
    FunctionType,
    ListType,
    LiteralType,
    NamedType,
    Type,
    UnionType,
    UnknownType,
    type_from_dict,
    type_to_dict,
)
from ._module import Module

__all__ = [
    "AnyType",
    "Arguments",
    "AssertStmt",
    "AssignStmt",
    "AugAssignStmt",
    "AugOp",
    "BasicType",
    "BinOp",
    "BinaryExpr",
    "CallExpr",
    "CheckExpr",
    "CmpOp",
    "Comment",
    "CompClause",
    "Compare",
    "ConfigEntry",
    "ConfigEntryOperation",
    "ConfigExpr",
    "ConfigIfEntryExpr",
    "Decorator",
    "DictComp",
    "DictType",
    "Expr",
    "ExprContext",
    "ExprStmt",
    "FormattedValue",
    "FunctionType",
    "Identifier",
    "IdentifierExpr",
    "IfExpr",
    "IfStmt",
    "ImportStmt",
    "IntLiteralType",
    "JoinedString",
    "KeyValuePair",
    "Keyword",
    "LambdaExpr",
    "ListComp",
    "ListExpr",
    "ListIfItemExpr",
    "ListType",
    "LiteralType",
    "MemberOrIndex",
    "MissingExpr",
    "Module",
    "NameConstantLit",
    "NamedType",
    "Node",
    "NumberBinarySuffix",
    "NumberLit",
    "NumberLitValue",
    "ParenExpr",
    "Pos",
    "QuantExpr",
    "QuantOperation",
    "RuleStmt",
    "SchemaAttr",
    "SchemaConfig",
    "SchemaExpr",
    "SchemaIndexSignature",
    "SchemaStmt",
    "SelectorExpr",
    "StarredExpr",
    "Stmt",
    "StringLit",
    "Subscript",
    "Target",
    "TargetExpr",
    "Type",
    "TypeAliasStmt",
    "UnaryExpr",
    "UnaryOp",
    "UnificationStmt",
    "UnionType",
    "UnknownExpr",
    "UnknownStmt",
    "UnknownType",
    "expr_from_dict",
    "expr_to_dict",
    "node_from_dict",
    "node_list_from_dict",
    "node_to_dict",
    "optional_node_list_from_dict",
    "optional_node_list_to_dict",
    "parse_module",
    "parse_program",
    "stmt_from_dict",
    "stmt_to_dict",
    "type_from_dict",
    "type_to_dict",
]
