"""Typed AST package for the KCL Python binding.

The AST JSON wire format is whatever the Rust compiler in
`kcl-lang/kcl/crates/ast/src/ast.rs` emits via `serde_json`. This package
mirrors that shape as Python dataclasses so Python callers can consume the
`ast_json` field returned by `api.parse_file` / `api.parse_program` as
typed objects rather than raw `dict`s.

Public surface (selected):

    from kcl_lib.ast import Module, SchemaStmt, ConfigEntry, parse_module
    module = parse_module(api.parse_file(args).ast_json)

Polymorphic nodes (``Expr`` and ``Stmt``) dispatch on the Rust ``"type"``
discriminator. The flat `Decorator` and `SchemaConfig` DTOs are kept as
distinct classes for the nested-under-``NodeRef`` shapes that lose the
discriminator (see `kcl-lang/lib` ``AST_DRIFT.md`` note A).
"""

from ._base import (
    Comment,
    Node,
    Pos,
    parse_module,
    parse_program,
)
from ._dto import (
    Arguments,
    ConfigEntry,
    ConfigEntryValue,
    ConfigExprEntry,
    Decorator,
    DecoratorList,
    DecoratorTarget,
    IfStmtBranch,
    JoinedStringPart,
    JoinedStringValue,
    Keyword,
    MemberOrIndex,
    ModuleRef,
    NumberLitSuffix,
    NumberLitValue,
    Program,
    QuantOperation,
    SchemaAttrDecorator,
    SchemaConfig,
    SchemaIndexSignature,
    SchemaIndexSignatureAttr,
    SchemaStmtBodyItem,
    Target as TargetDTO,
)
from ._expr import (
    BinaryExpr,
    CallExpr,
    CheckExpr,
    CompClause,
    Compare,
    ConfigExpr,
    ConfigIfEntryExpr,
    DictComp,
    Expr,
    ExprContext,
    FormattedValue,
    Identifier,
    IfExpr,
    JoinedString,
    LambdaExpr,
    ListComp,
    ListExpr,
    ListIfItemExpr,
    MissingExpr,
    NameConstant,
    NameConstantLit,
    NumberLit,
    ParenExpr,
    QuantExpr,
    SchemaExpr,
    SelectorExpr,
    StarredExpr,
    StringLit,
    Subscript,
    Target,
    UnaryExpr,
    expr_from_dict,
)
from ._module import Module
from ._op import (
    AugOp,
    BinOp,
    ConfigEntryOperation,
    CmpOp,
    NumberBinarySuffix,
    QuantOperation,
    UnaryOp,
)
from ._stmt import (
    AssertStmt,
    AssignStmt,
    AugAssignStmt,
    ExprStmt,
    IfStmt,
    ImportStmt,
    RuleStmt,
    SchemaAttr,
    SchemaStmt,
    Stmt,
    TypeAliasStmt,
    UnificationStmt,
    stmt_from_dict,
)
from ._types import (
    AnyType,
    BasicType,
    BoolLiteralType,
    DictType,
    FloatLiteralType,
    FunctionType,
    IntLiteralType,
    KeyValueType,
    ListType,
    LiteralType,
    NamedType,
    SchemaRefType,
    StrLiteralType,
    Type,
    UnionType,
    type_from_dict,
)

__all__ = [
    # base
    "Comment",
    "Node",
    "Pos",
    "parse_module",
    "parse_program",
    # module
    "Module",
    # expr
    "BinaryExpr",
    "CallExpr",
    "CheckExpr",
    "CompClause",
    "Compare",
    "ConfigExpr",
    "ConfigIfEntryExpr",
    "DictComp",
    "Expr",
    "ExprContext",
    "FormattedValue",
    "Identifier",
    "IfExpr",
    "JoinedString",
    "LambdaExpr",
    "ListComp",
    "ListExpr",
    "ListIfItemExpr",
    "MissingExpr",
    "NameConstant",
    "NameConstantLit",
    "NumberLit",
    "ParenExpr",
    "QuantExpr",
    "SchemaExpr",
    "SelectorExpr",
    "StarredExpr",
    "StringLit",
    "Subscript",
    "Target",
    "UnaryExpr",
    "expr_from_dict",
    # stmt
    "AssertStmt",
    "AssignStmt",
    "AugAssignStmt",
    "ExprStmt",
    "IfStmt",
    "ImportStmt",
    "RuleStmt",
    "SchemaAttr",
    "SchemaStmt",
    "Stmt",
    "TypeAliasStmt",
    "UnificationStmt",
    "stmt_from_dict",
    # dto
    "Arguments",
    "ConfigEntry",
    "ConfigEntryValue",
    "ConfigExprEntry",
    "Decorator",
    "DecoratorList",
    "DecoratorTarget",
    "IfStmtBranch",
    "JoinedStringPart",
    "JoinedStringValue",
    "Keyword",
    "MemberOrIndex",
    "ModuleRef",
    "NumberLitSuffix",
    "NumberLitValue",
    "Program",
    "QuantOperation",
    "SchemaAttrDecorator",
    "SchemaConfig",
    "SchemaIndexSignature",
    "SchemaIndexSignatureAttr",
    "SchemaStmtBodyItem",
    "TargetDTO",
    # op
    "AugOp",
    "BinOp",
    "ConfigEntryOperation",
    "CmpOp",
    "NumberBinarySuffix",
    "QuantOperation",
    "UnaryOp",
    # types
    "AnyType",
    "BasicType",
    "BoolLiteralType",
    "DictType",
    "FloatLiteralType",
    "FunctionType",
    "IntLiteralType",
    "KeyValueType",
    "ListType",
    "LiteralType",
    "NamedType",
    "SchemaRefType",
    "StrLiteralType",
    "Type",
    "UnionType",
    "type_from_dict",
]