# Code generated by tools/generate_ast.py from
# kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb556472737).
# DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
# result, or `ruby hack/check_generated_ast.rb` will fail.
#
# Every class, field, wire tag and operator below is derived from the Rust
# source. The prose is not; see tools/astgen/narrative.py.
"""Statement hierarchy — mirrors ``ast::Stmt`` in
``kcl-lang/kcl/crates/ast/src/ast.rs``.

The Rust enum is internally tagged with no ``rename_all``::

    #[serde(tag = "type")]
    pub enum Stmt {
        TypeAlias(TypeAliasStmt), Expr(ExprStmt), Unification(UnificationStmt),
        Assign(AssignStmt), AugAssign(AugAssignStmt), Assert(AssertStmt),
        If(IfStmt), Import(ImportStmt), SchemaAttr(SchemaAttr),
        Schema(SchemaStmt), Rule(RuleStmt),
    }

As with ``Expr``, the variant's struct fields are flattened into the same
object as the tag, so ``stmt_from_dict`` hands the whole dict to the variant.

Fields typed with a *struct* rather than an enum variant lose the tag even
inside a tagged statement: ``SchemaStmt.decorators`` is
``Vec<NodeRef<CallExpr>>``, so a decorator is a bare ``{func, args, keywords}``,
and ``SchemaStmt.checks`` is ``Vec<NodeRef<CheckExpr>>``, so a check is a bare
``{test, if_cond, msg}``. Both classes live in ``_dto.py``."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from ._base import (
    Node,
    node_from_dict,
    node_list_from_dict,
    node_list_to_dict,
    node_to_dict,
)


@dataclass
class Stmt:
    """Base class. Concrete variants add their fields and override both hooks."""

    @classmethod
    def from_dict(cls, d: Any) -> "Stmt":
        raise NotImplementedError

    def to_dict(self) -> dict:
        raise NotImplementedError

@dataclass
class UnknownStmt(Stmt):
    """A ``Stmt`` variant this build does not know about, preserved verbatim."""

    tag: str = ""
    value: Any = None

    @classmethod
    def from_dict(cls, d: Any) -> "UnknownStmt":
        return cls(tag=str(d.get("type") or ""), value=d)

    def to_dict(self) -> dict:
        return self.value if isinstance(self.value, dict) else {"type": self.tag}

# --- AssertStmt --------------------------------------------------------

@dataclass
class AssertStmt(Stmt):
    """``Stmt::Assert``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct AssertStmt {``
        pub test: NodeRef<Expr>,
        pub if_cond: Option<NodeRef<Expr>>,
        pub msg: Option<NodeRef<Expr>>,
    }``
    """

    test: Optional[Node] = None
    if_cond: Optional[Node] = None
    msg: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "AssertStmt":
        from ._expr import expr_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            test=node_from_dict(d.get("test"), expr_from_dict),
            if_cond=node_from_dict(d.get("if_cond"), expr_from_dict),
            msg=node_from_dict(d.get("msg"), expr_from_dict),
        )

    def to_dict(self) -> dict:
        from ._expr import expr_to_dict

        out = {
            "test": node_to_dict(self.test, expr_to_dict),
            "if_cond": node_to_dict(self.if_cond, expr_to_dict),
            "msg": node_to_dict(self.msg, expr_to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Assert"
        return out


# --- AssignStmt --------------------------------------------------------

@dataclass
class AssignStmt(Stmt):
    """``Stmt::Assign``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct AssignStmt {``
        pub targets: Vec<NodeRef<Target>>,
        pub value: NodeRef<Expr>,
        pub ty: Option<NodeRef<Type>>,
    }``
    """

    targets: List[Node] = field(default_factory=list)
    value: Optional[Node] = None
    ty: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "AssignStmt":
        from ._dto import Target
        from ._expr import expr_from_dict
        from ._types import type_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            targets=node_list_from_dict(d.get("targets"), Target.from_dict),
            value=node_from_dict(d.get("value"), expr_from_dict),
            ty=node_from_dict(d.get("ty"), type_from_dict),
        )

    def to_dict(self) -> dict:
        from ._dto import Target
        from ._expr import expr_to_dict
        from ._types import type_to_dict

        out = {
            "targets": node_list_to_dict(self.targets, Target.to_dict),
            "value": node_to_dict(self.value, expr_to_dict),
            "ty": node_to_dict(self.ty, type_to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Assign"
        return out


# --- AugAssignStmt -----------------------------------------------------

@dataclass
class AugAssignStmt(Stmt):
    """``Stmt::AugAssign``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct AugAssignStmt {``
        pub target: NodeRef<Target>,
        pub value: NodeRef<Expr>,
        pub op: AugOp,
    }``
    """

    target: Optional[Node] = None
    value: Optional[Node] = None
    op: str = ""

    @classmethod
    def from_dict(cls, d: Any) -> "AugAssignStmt":
        from ._dto import Target
        from ._expr import expr_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            target=node_from_dict(d.get("target"), Target.from_dict),
            value=node_from_dict(d.get("value"), expr_from_dict),
            op=d.get("op") or "",
        )

    def to_dict(self) -> dict:
        from ._dto import Target
        from ._expr import expr_to_dict

        out = {
            "target": node_to_dict(self.target, Target.to_dict),
            "value": node_to_dict(self.value, expr_to_dict),
            "op": self.op,
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "AugAssign"
        return out


# --- ExprStmt ----------------------------------------------------------

@dataclass
class ExprStmt(Stmt):
    """``Stmt::Expr``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct ExprStmt {``
        pub exprs: Vec<NodeRef<Expr>>,
    }``
    """

    exprs: List[Node] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: Any) -> "ExprStmt":
        from ._expr import expr_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            exprs=node_list_from_dict(d.get("exprs"), expr_from_dict),
        )

    def to_dict(self) -> dict:
        from ._expr import expr_to_dict

        out = {
            "exprs": node_list_to_dict(self.exprs, expr_to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Expr"
        return out


# --- IfStmt ------------------------------------------------------------

@dataclass
class IfStmt(Stmt):
    """``Stmt::If``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct IfStmt {``
        pub body: Vec<NodeRef<Stmt>>,
        pub cond: NodeRef<Expr>,
        pub orelse: Vec<NodeRef<Stmt>>,
    }``
    """

    body: List[Node] = field(default_factory=list)
    cond: Optional[Node] = None
    orelse: List[Node] = field(default_factory=list)

    @classmethod
    def from_dict(cls, d: Any) -> "IfStmt":
        from ._expr import expr_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            body=node_list_from_dict(d.get("body"), stmt_from_dict),
            cond=node_from_dict(d.get("cond"), expr_from_dict),
            orelse=node_list_from_dict(d.get("orelse"), stmt_from_dict),
        )

    def to_dict(self) -> dict:
        from ._expr import expr_to_dict

        out = {
            "body": node_list_to_dict(self.body, stmt_to_dict),
            "cond": node_to_dict(self.cond, expr_to_dict),
            "orelse": node_list_to_dict(self.orelse, stmt_to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "If"
        return out


# --- ImportStmt --------------------------------------------------------

@dataclass
class ImportStmt(Stmt):
    """``Stmt::Import``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct ImportStmt {``
        pub path: Node<String>,
        pub rawpath: String,
        pub name: String,
        pub asname: Option<Node<String>>,
        pub pkg_name: String,
    }``
    """

    path: Optional[Node] = None
    rawpath: str = ""
    name: str = ""
    asname: Optional[Node] = None
    pkg_name: str = ""

    @classmethod
    def from_dict(cls, d: Any) -> "ImportStmt":
        d = d if isinstance(d, dict) else {}
        return cls(
            path=node_from_dict(d.get("path")),
            rawpath=d.get("rawpath") or "",
            name=d.get("name") or "",
            asname=node_from_dict(d.get("asname")),
            pkg_name=d.get("pkg_name") or "",
        )

    def to_dict(self) -> dict:
        out = {
            "path": node_to_dict(self.path),
            "rawpath": self.rawpath,
            "name": self.name,
            "asname": node_to_dict(self.asname),
            "pkg_name": self.pkg_name,
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Import"
        return out


# --- RuleStmt ----------------------------------------------------------

@dataclass
class RuleStmt(Stmt):
    """``Stmt::Rule``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct RuleStmt {``
        pub doc: Option<NodeRef<String>>,
        pub name: NodeRef<String>,
        pub parent_rules: Vec<NodeRef<Identifier>>,
        pub decorators: Vec<NodeRef<CallExpr>>,
        pub checks: Vec<NodeRef<CheckExpr>>,
        pub args: Option<NodeRef<Arguments>>,
        pub for_host_name: Option<NodeRef<Identifier>>,
    }``
    """

    doc: Optional[Node] = None
    name: Optional[Node] = None
    parent_rules: List[Node] = field(default_factory=list)
    decorators: List[Node] = field(default_factory=list)
    checks: List[Node] = field(default_factory=list)
    args: Optional[Node] = None
    for_host_name: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "RuleStmt":
        from ._dto import Arguments, CallExpr, CheckExpr, Identifier

        d = d if isinstance(d, dict) else {}
        return cls(
            doc=node_from_dict(d.get("doc")),
            name=node_from_dict(d.get("name")),
            parent_rules=node_list_from_dict(d.get("parent_rules"), Identifier.from_dict),
            decorators=node_list_from_dict(d.get("decorators"), CallExpr.from_dict),
            checks=node_list_from_dict(d.get("checks"), CheckExpr.from_dict),
            args=node_from_dict(d.get("args"), Arguments.from_dict),
            for_host_name=node_from_dict(d.get("for_host_name"), Identifier.from_dict),
        )

    def to_dict(self) -> dict:
        from ._dto import Arguments, CallExpr, CheckExpr, Identifier

        out = {
            "doc": node_to_dict(self.doc),
            "name": node_to_dict(self.name),
            "parent_rules": node_list_to_dict(self.parent_rules, Identifier.to_dict),
            "decorators": node_list_to_dict(self.decorators, CallExpr.to_dict),
            "checks": node_list_to_dict(self.checks, CheckExpr.to_dict),
            "args": node_to_dict(self.args, Arguments.to_dict),
            "for_host_name": node_to_dict(self.for_host_name, Identifier.to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Rule"
        return out


# --- SchemaStmt --------------------------------------------------------

@dataclass
class SchemaStmt(Stmt):
    """``Stmt::Schema``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct SchemaStmt {``
        pub doc: Option<NodeRef<String>>,
        pub name: NodeRef<String>,
        pub parent_name: Option<NodeRef<Identifier>>,
        pub for_host_name: Option<NodeRef<Identifier>>,
        pub is_mixin: bool,
        pub is_protocol: bool,
        pub args: Option<NodeRef<Arguments>>,
        pub mixins: Vec<NodeRef<Identifier>>,
        pub body: Vec<NodeRef<Stmt>>,
        pub decorators: Vec<NodeRef<CallExpr>>,
        pub checks: Vec<NodeRef<CheckExpr>>,
        pub index_signature: Option<NodeRef<SchemaIndexSignature>>,
    }``
    """

    doc: Optional[Node] = None
    name: Optional[Node] = None
    parent_name: Optional[Node] = None
    for_host_name: Optional[Node] = None
    is_mixin: bool = False
    is_protocol: bool = False
    args: Optional[Node] = None
    mixins: List[Node] = field(default_factory=list)
    body: List[Node] = field(default_factory=list)
    decorators: List[Node] = field(default_factory=list)
    checks: List[Node] = field(default_factory=list)
    index_signature: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "SchemaStmt":
        from ._dto import Arguments, CallExpr, CheckExpr, Identifier, SchemaIndexSignature

        d = d if isinstance(d, dict) else {}
        return cls(
            doc=node_from_dict(d.get("doc")),
            name=node_from_dict(d.get("name")),
            parent_name=node_from_dict(d.get("parent_name"), Identifier.from_dict),
            for_host_name=node_from_dict(d.get("for_host_name"), Identifier.from_dict),
            is_mixin=bool(d.get("is_mixin") or False),
            is_protocol=bool(d.get("is_protocol") or False),
            args=node_from_dict(d.get("args"), Arguments.from_dict),
            mixins=node_list_from_dict(d.get("mixins"), Identifier.from_dict),
            body=node_list_from_dict(d.get("body"), stmt_from_dict),
            decorators=node_list_from_dict(d.get("decorators"), CallExpr.from_dict),
            checks=node_list_from_dict(d.get("checks"), CheckExpr.from_dict),
            index_signature=node_from_dict(d.get("index_signature"), SchemaIndexSignature.from_dict),
        )

    def to_dict(self) -> dict:
        from ._dto import Arguments, CallExpr, CheckExpr, Identifier, SchemaIndexSignature

        out = {
            "doc": node_to_dict(self.doc),
            "name": node_to_dict(self.name),
            "parent_name": node_to_dict(self.parent_name, Identifier.to_dict),
            "for_host_name": node_to_dict(self.for_host_name, Identifier.to_dict),
            "is_mixin": self.is_mixin,
            "is_protocol": self.is_protocol,
            "args": node_to_dict(self.args, Arguments.to_dict),
            "mixins": node_list_to_dict(self.mixins, Identifier.to_dict),
            "body": node_list_to_dict(self.body, stmt_to_dict),
            "decorators": node_list_to_dict(self.decorators, CallExpr.to_dict),
            "checks": node_list_to_dict(self.checks, CheckExpr.to_dict),
            "index_signature": node_to_dict(self.index_signature, SchemaIndexSignature.to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Schema"
        return out

    def schema_name(self) -> str:
        """``SchemaStmt::get_name()`` in Rust."""
        return self.name.node if self.name is not None and isinstance(self.name.node, str) else ""


# --- SchemaAttr --------------------------------------------------------

@dataclass
class SchemaAttr(Stmt):
    """``Stmt::SchemaAttr``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct SchemaAttr {``
        pub doc: String,
        pub name: NodeRef<String>,
        pub op: Option<AugOp>,
        pub value: Option<NodeRef<Expr>>,
        pub is_optional: bool,
        pub decorators: Vec<NodeRef<CallExpr>>,
        pub ty: NodeRef<Type>,
    }``
    """

    doc: str = ""
    name: Optional[Node] = None
    op: Optional[str] = None
    value: Optional[Node] = None
    is_optional: bool = False
    decorators: List[Node] = field(default_factory=list)
    ty: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "SchemaAttr":
        from ._dto import CallExpr
        from ._expr import expr_from_dict
        from ._types import type_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            doc=d.get("doc") or "",
            name=node_from_dict(d.get("name")),
            op=d.get("op"),
            value=node_from_dict(d.get("value"), expr_from_dict),
            is_optional=bool(d.get("is_optional") or False),
            decorators=node_list_from_dict(d.get("decorators"), CallExpr.from_dict),
            ty=node_from_dict(d.get("ty"), type_from_dict),
        )

    def to_dict(self) -> dict:
        from ._dto import CallExpr
        from ._expr import expr_to_dict
        from ._types import type_to_dict

        out = {
            "doc": self.doc,
            "name": node_to_dict(self.name),
            "op": self.op,
            "value": node_to_dict(self.value, expr_to_dict),
            "is_optional": self.is_optional,
            "decorators": node_list_to_dict(self.decorators, CallExpr.to_dict),
            "ty": node_to_dict(self.ty, type_to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "SchemaAttr"
        return out


# --- TypeAliasStmt -----------------------------------------------------

@dataclass
class TypeAliasStmt(Stmt):
    """``Stmt::TypeAlias``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct TypeAliasStmt {``
        pub type_name: NodeRef<Identifier>,
        pub type_value: NodeRef<String>,
        pub ty: NodeRef<Type>,
    }``
    """

    type_name: Optional[Node] = None
    type_value: Optional[Node] = None
    ty: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "TypeAliasStmt":
        from ._dto import Identifier
        from ._types import type_from_dict

        d = d if isinstance(d, dict) else {}
        return cls(
            type_name=node_from_dict(d.get("type_name"), Identifier.from_dict),
            type_value=node_from_dict(d.get("type_value")),
            ty=node_from_dict(d.get("ty"), type_from_dict),
        )

    def to_dict(self) -> dict:
        from ._dto import Identifier
        from ._types import type_to_dict

        out = {
            "type_name": node_to_dict(self.type_name, Identifier.to_dict),
            "type_value": node_to_dict(self.type_value),
            "ty": node_to_dict(self.ty, type_to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "TypeAlias"
        return out


# --- UnificationStmt ---------------------------------------------------

@dataclass
class UnificationStmt(Stmt):
    """``Stmt::Unification``.

    Internally tagged with **no** ``rename_all``, so the wire tag is
    the variant name verbatim and the struct's fields are *flattened into
    the same object as the tag*. There is no wrapper key to descend
    through.

    Rust declares ``pub struct UnificationStmt {``
        pub target: NodeRef<Identifier>,
        pub value: NodeRef<SchemaExpr>,
    }``
    """

    target: Optional[Node] = None
    value: Optional[Node] = None

    @classmethod
    def from_dict(cls, d: Any) -> "UnificationStmt":
        from ._dto import Identifier, SchemaExpr

        d = d if isinstance(d, dict) else {}
        return cls(
            target=node_from_dict(d.get("target"), Identifier.from_dict),
            value=node_from_dict(d.get("value"), SchemaExpr.from_dict),
        )

    def to_dict(self) -> dict:
        from ._dto import Identifier, SchemaExpr

        out = {
            "target": node_to_dict(self.target, Identifier.to_dict),
            "value": node_to_dict(self.value, SchemaExpr.to_dict),
        }
        # The tag goes back on under its own key, because the
        # variant's fields were flattened into this same object.
        out["type"] = "Unification"
        return out




_STMT_REGISTRY: Optional[Dict[str, Any]] = None
_STMT_TAGS_BY_CLASS: Dict[type, str] = {}


def _stmt_registry() -> Dict[str, Any]:
    """Wire tag -> class, in the order ``ast.rs`` declares the variants.

    Built on first use rather than at import time: see the note above.
    """
    global _STMT_REGISTRY, _STMT_TAGS_BY_CLASS
    if _STMT_REGISTRY is None:
        _STMT_REGISTRY = {
            "TypeAlias": TypeAliasStmt,
            "Expr": ExprStmt,
            "Unification": UnificationStmt,
            "Assign": AssignStmt,
            "AugAssign": AugAssignStmt,
            "Assert": AssertStmt,
            "If": IfStmt,
            "Import": ImportStmt,
            "SchemaAttr": SchemaAttr,
            "Schema": SchemaStmt,
            "Rule": RuleStmt,
}
        _STMT_TAGS_BY_CLASS = {cls: tag for tag, cls in _STMT_REGISTRY.items()}
    return _STMT_REGISTRY


def _stmt_tag_for(cls: type) -> Optional[str]:
    """The wire tag for a variant class — the inverse of the registry."""
    if not _STMT_TAGS_BY_CLASS:
        _stmt_registry()
    return _STMT_TAGS_BY_CLASS.get(cls)


def stmt_from_dict(d: Any) -> Any:
    """Polymorphic ``Stmt`` loader — the mirror of :func:`stmt_to_dict`.

    An unrecognised tag decodes to :class:`UnknownStmt`, which keeps the raw
    tag and payload so a forward-compatible parser output survives the round
    trip instead of being dropped.
    """
    d = d if isinstance(d, dict) else {}
    tag = d.get("type") or ""
    cls = _stmt_registry().get(tag)
    if cls is None:
        return UnknownStmt.from_dict(d)
    return cls.from_dict(d)


def stmt_to_dict(s: Any) -> Any:
    """Polymorphic ``Stmt`` serializer — the mirror of :func:`stmt_from_dict`."""
    if s is None:
        return None
    if isinstance(s, UnknownStmt):
        return s.to_dict()
    tag = _stmt_tag_for(type(s))
    if tag is None:
        raise TypeError("not a Stmt variant: %s" % type(s).__name__)
    out = {"type": tag}
    out.update(s.to_dict())
    return out

__all__ = [
    "AssertStmt",
    "AssignStmt",
    "AugAssignStmt",
    "ExprStmt",
    "IfStmt",
    "ImportStmt",
    "RuleStmt",
    "SchemaAttr",
    "SchemaStmt",
    "Stmt",
    "TypeAliasStmt",
    "UnificationStmt",
    "UnknownStmt",
    "stmt_from_dict",
    "stmt_to_dict",
]
