// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializebuildProgramResult")
public inline fun buildProgramResult(block: com.kcl.api.BuildProgramResultKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.BuildProgramResult =
  com.kcl.api.BuildProgramResultKt.Dsl._create(com.kcl.api.Spec.BuildProgramResult.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for build program response.
 * ```
 *
 * Protobuf type `com.kcl.api.BuildProgramResult`
 */
public object BuildProgramResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.BuildProgramResult.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.BuildProgramResult.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.BuildProgramResult = _builder.build()

    /**
     * ```
     * Path of the built program.
     * ```
     *
     * `string path = 1;`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * ```
     * Path of the built program.
     * ```
     *
     * `string path = 1;`
     */
    public fun clearPath() {
      _builder.clearPath()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.BuildProgramResult.copy(block: `com.kcl.api`.BuildProgramResultKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.BuildProgramResult =
  `com.kcl.api`.BuildProgramResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

