// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializeformatCodeResult")
public inline fun formatCodeResult(block: com.kcl.api.FormatCode_ResultKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.FormatCode_Result =
  com.kcl.api.FormatCode_ResultKt.Dsl._create(com.kcl.api.Spec.FormatCode_Result.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for format code response.
 * ```
 *
 * Protobuf type `com.kcl.api.FormatCode_Result`
 */
public object FormatCode_ResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.FormatCode_Result.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.FormatCode_Result.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.FormatCode_Result = _builder.build()

    /**
     * ```
     * Formatted code as bytes.
     * ```
     *
     * `bytes formatted = 1;`
     */
    public var formatted: com.google.protobuf.ByteString
      @JvmName("getFormatted")
      get() = _builder.formatted
      @JvmName("setFormatted")
      set(value) {
        _builder.formatted = value
      }
    /**
     * ```
     * Formatted code as bytes.
     * ```
     *
     * `bytes formatted = 1;`
     */
    public fun clearFormatted() {
      _builder.clearFormatted()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.FormatCode_Result.copy(block: `com.kcl.api`.FormatCode_ResultKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.FormatCode_Result =
  `com.kcl.api`.FormatCode_ResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

