// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializegenerateTomlArgs")
public inline fun generateTomlArgs(block: com.kcl.api.GenerateTomlArgsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.GenerateTomlArgs =
  com.kcl.api.GenerateTomlArgsKt.Dsl._create(com.kcl.api.Spec.GenerateTomlArgs.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for generate TOML request arguments.
 * ```
 *
 * Protobuf type `com.kcl.api.GenerateTomlArgs`
 */
public object GenerateTomlArgsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.GenerateTomlArgs.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.GenerateTomlArgs.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.GenerateTomlArgs = _builder.build()

    /**
     * ```
     * Arguments for executing the program whose result is serialized to TOML.
     * ```
     *
     * `.com.kcl.api.ExecProgramArgs exec_args = 1;`
     */
    public var execArgs: com.kcl.api.Spec.ExecProgramArgs
      @kotlin.jvm.JvmName("getExecArgs")
        get() = _builder.execArgs
      @kotlin.jvm.JvmName("setExecArgs")
        set(value) {
        _builder.execArgs = value
      }
    /**
     * ```
     * Arguments for executing the program whose result is serialized to TOML.
     * ```
     *
     * `.com.kcl.api.ExecProgramArgs exec_args = 1;`
     */
    public fun clearExecArgs() {
      _builder.clearExecArgs()
    }
    /**
     * ```
     * Arguments for executing the program whose result is serialized to TOML.
     * ```
     *
     * `.com.kcl.api.ExecProgramArgs exec_args = 1;`
     * @return Whether the execArgs field is set.
     */
    public fun hasExecArgs(): kotlin.Boolean {
      return _builder.hasExecArgs()
    }

    public val GenerateTomlArgsKt.Dsl.execArgsOrNull: com.kcl.api.Spec.ExecProgramArgs?
      get() = _builder.execArgsOrNull

    /**
     * ```
     * Flag to sort keys in the TOML output. Defaults to false (source order).
     * ```
     *
     * `bool sort_keys = 2;`
     */
    public var sortKeys: kotlin.Boolean
      @kotlin.jvm.JvmName("getSortKeys")
        get() = _builder.sortKeys
      @kotlin.jvm.JvmName("setSortKeys")
        set(value) {
        _builder.sortKeys = value
      }
    /**
     * ```
     * Flag to sort keys in the TOML output. Defaults to false (source order).
     * ```
     *
     * `bool sort_keys = 2;`
     */
    public fun clearSortKeys() {
      _builder.clearSortKeys()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.GenerateTomlArgs.copy(block: `com.kcl.api`.GenerateTomlArgsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.GenerateTomlArgs =
  `com.kcl.api`.GenerateTomlArgsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.kcl.api.Spec.GenerateTomlArgsOrBuilder.execArgsOrNull: com.kcl.api.Spec.ExecProgramArgs?
  get() = if (hasExecArgs()) getExecArgs() else null

