// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializelistVariablesOptions")
public inline fun listVariablesOptions(block: com.kcl.api.ListVariablesOptionsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.ListVariablesOptions =
  com.kcl.api.ListVariablesOptionsKt.Dsl._create(com.kcl.api.Spec.ListVariablesOptions.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for list variables options.
 * ```
 *
 * Protobuf type `com.kcl.api.ListVariablesOptions`
 */
public object ListVariablesOptionsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.ListVariablesOptions.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.ListVariablesOptions.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.ListVariablesOptions = _builder.build()

    /**
     * ```
     * Flag to merge program configuration.
     * ```
     *
     * `bool merge_program = 1;`
     */
    public var mergeProgram: kotlin.Boolean
      @kotlin.jvm.JvmName("getMergeProgram")
        get() = _builder.mergeProgram
      @kotlin.jvm.JvmName("setMergeProgram")
        set(value) {
        _builder.mergeProgram = value
      }
    /**
     * ```
     * Flag to merge program configuration.
     * ```
     *
     * `bool merge_program = 1;`
     */
    public fun clearMergeProgram() {
      _builder.clearMergeProgram()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.ListVariablesOptions.copy(block: `com.kcl.api`.ListVariablesOptionsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.ListVariablesOptions =
  `com.kcl.api`.ListVariablesOptionsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

