// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializelistDepFilesResult")
public inline fun listDepFilesResult(block: com.kcl.api.ListDepFiles_ResultKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.ListDepFiles_Result =
  com.kcl.api.ListDepFiles_ResultKt.Dsl._create(com.kcl.api.Spec.ListDepFiles_Result.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for list dependency files response.
 * ```
 *
 * Protobuf type `com.kcl.api.ListDepFiles_Result`
 */
public object ListDepFiles_ResultKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.ListDepFiles_Result.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.ListDepFiles_Result.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.ListDepFiles_Result = _builder.build()

    /**
     * ```
     * Root package path.
     * ```
     *
     * `string pkgroot = 1;`
     */
    public var pkgroot: kotlin.String
      @JvmName("getPkgroot")
      get() = _builder.pkgroot
      @JvmName("setPkgroot")
      set(value) {
        _builder.pkgroot = value
      }
    /**
     * ```
     * Root package path.
     * ```
     *
     * `string pkgroot = 1;`
     */
    public fun clearPkgroot() {
      _builder.clearPkgroot()
    }

    /**
     * ```
     * Package path.
     * ```
     *
     * `string pkgpath = 2;`
     */
    public var pkgpath: kotlin.String
      @JvmName("getPkgpath")
      get() = _builder.pkgpath
      @JvmName("setPkgpath")
      set(value) {
        _builder.pkgpath = value
      }
    /**
     * ```
     * Package path.
     * ```
     *
     * `string pkgpath = 2;`
     */
    public fun clearPkgpath() {
      _builder.clearPkgpath()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FilesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     * @return A list containing the files.
     */
    public val files: com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.filesList
      )
    /**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     * @param value The files to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addFiles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.add(value: kotlin.String) {
      _builder.addFiles(value)
    }
    /**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     * @param value The files to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignFiles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     * @param values The files to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllFiles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllFiles(values)
    }
    /**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     * @param values The files to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllFiles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     * @param index The index to set the value at.
     * @param value The files to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setFiles")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setFiles(index, value)
    }/**
     * ```
     * List of file paths in the package.
     * ```
     *
     * `repeated string files = 3;`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearFiles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.clear() {
      _builder.clearFiles()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.ListDepFiles_Result.copy(block: `com.kcl.api`.ListDepFiles_ResultKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.ListDepFiles_Result =
  `com.kcl.api`.ListDepFiles_ResultKt.Dsl._create(this.toBuilder()).apply { block() }._build()

