// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializeloadSettingsFilesArgs")
public inline fun loadSettingsFilesArgs(block: com.kcl.api.LoadSettingsFilesArgsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.LoadSettingsFilesArgs =
  com.kcl.api.LoadSettingsFilesArgsKt.Dsl._create(com.kcl.api.Spec.LoadSettingsFilesArgs.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for load settings files request arguments.
 * ```
 *
 * Protobuf type `com.kcl.api.LoadSettingsFilesArgs`
 */
public object LoadSettingsFilesArgsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.LoadSettingsFilesArgs.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.LoadSettingsFilesArgs.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.LoadSettingsFilesArgs = _builder.build()

    /**
     * ```
     * Working directory.
     * ```
     *
     * `string work_dir = 1;`
     */
    public var workDir: kotlin.String
      @kotlin.jvm.JvmName("getWorkDir")
        get() = _builder.workDir
      @kotlin.jvm.JvmName("setWorkDir")
        set(value) {
        _builder.workDir = value
      }
    /**
     * ```
     * Working directory.
     * ```
     *
     * `string work_dir = 1;`
     */
    public fun clearWorkDir() {
      _builder.clearWorkDir()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class FilesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     * @return A list containing the files.
     */
    public val files: com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.filesList
      )
    /**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     * @param value The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addFiles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.add(value: kotlin.String) {
      _builder.addFiles(value)
    }
    /**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     * @param value The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignFiles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     * @param values The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllFiles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllFiles(values)
    }
    /**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     * @param values The files to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllFiles")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     * @param index The index to set the value at.
     * @param value The files to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setFiles")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setFiles(index, value)
    }/**
     * ```
     * Setting files to load.
     * ```
     *
     * `repeated string files = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setFiles")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, FilesProxy>.clear() {
      _builder.clearFiles()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.LoadSettingsFilesArgs.copy(block: `com.kcl.api`.LoadSettingsFilesArgsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.LoadSettingsFilesArgs =
  `com.kcl.api`.LoadSettingsFilesArgsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

