// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializeparameter")
public inline fun parameter(block: com.kcl.api.ParameterKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.Parameter =
  com.kcl.api.ParameterKt.Dsl._create(com.kcl.api.Spec.Parameter.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.kcl.api.Parameter`
 */
public object ParameterKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.Parameter.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.Parameter.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.Parameter = _builder.build()

    /**
     * `string name = 1;`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1;`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.com.kcl.api.KclType ty = 2;`
     */
    public var ty: com.kcl.api.Spec.KclType
      @kotlin.jvm.JvmName("getTy")
        get() = _builder.ty
      @kotlin.jvm.JvmName("setTy")
        set(value) {
        _builder.ty = value
      }
    /**
     * `.com.kcl.api.KclType ty = 2;`
     */
    public fun clearTy() {
      _builder.clearTy()
    }
    /**
     * `.com.kcl.api.KclType ty = 2;`
     * @return Whether the ty field is set.
     */
    public fun hasTy(): kotlin.Boolean {
      return _builder.hasTy()
    }

    public val ParameterKt.Dsl.tyOrNull: com.kcl.api.Spec.KclType?
      get() = _builder.tyOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.Parameter.copy(block: `com.kcl.api`.ParameterKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.Parameter =
  `com.kcl.api`.ParameterKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.kcl.api.Spec.ParameterOrBuilder.tyOrNull: com.kcl.api.Spec.KclType?
  get() = if (hasTy()) getTy() else null

