// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spec.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.kcl.api;

@kotlin.jvm.JvmName("-initializepingArgs")
public inline fun pingArgs(block: com.kcl.api.Ping_ArgsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.Ping_Args =
  com.kcl.api.Ping_ArgsKt.Dsl._create(com.kcl.api.Spec.Ping_Args.newBuilder()).apply { block() }._build()
/**
 * ```
 * Message for ping request arguments.
 * ```
 *
 * Protobuf type `com.kcl.api.Ping_Args`
 */
public object Ping_ArgsKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.kcl.api.Spec.Ping_Args.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.kcl.api.Spec.Ping_Args.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.kcl.api.Spec.Ping_Args = _builder.build()

    /**
     * ```
     * Value to be sent in the ping request.
     * ```
     *
     * `string value = 1;`
     */
    public var value: kotlin.String
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * ```
     * Value to be sent in the ping request.
     * ```
     *
     * `string value = 1;`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.kcl.api.Spec.Ping_Args.copy(block: `com.kcl.api`.Ping_ArgsKt.Dsl.() -> kotlin.Unit): com.kcl.api.Spec.Ping_Args =
  `com.kcl.api`.Ping_ArgsKt.Dsl._create(this.toBuilder()).apply { block() }._build()

