<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>astdump</AssemblyName>
    <RootNamespace>AstDump</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../dotnet/KclLib.AST/KclLib.AST.csproj" />
  </ItemGroup>
</Project>
