local json = require("dkjson")
local pl_path = require("pl.path")

local api = require("kcl_lib.raw_api")

-- Cross-language consistency runner: executes the hermetic cases from
-- `tests/consistency/cases.json` (generated by
-- `tests/consistency/generate_cases.py`) and asserts the same golden
-- expectations as the python/nodejs/go/java/dotnet runners.
--
-- Run it with:
--
--     luarocks test ./*.rockspec
--
-- `spec/` is two levels below the repository root, which is also two levels
-- above `tests/consistency/cases.json`. Resolve against this file rather than
-- the working directory so the suite behaves the same whether busted is
-- invoked from `lua/` or from the repository root.

local SPEC_DIR = pl_path.dirname(
  debug.getinfo(1, "S").source:gsub("^@", "")
)
local REPO_ROOT = pl_path.abspath(pl_path.join(SPEC_DIR, "..", ".."))
local CASES_JSON = pl_path.join(REPO_ROOT, "tests", "consistency", "cases.json")

---Read `node[key]`, falling back to `default` when the key is absent or JSON
---`null` (`dkjson.null`).
---@param node any
---@param key string
---@param default any
---@return any
local function field(node, key, default)
  if type(node) ~= "table" then
    return default
  end
  local v = node[key]
  if v == nil or v == json.null then
    return default
  end
  return v
end

---@return table manifest
local function manifest()
  local fh, err = io.open(CASES_JSON, "r")
  if not fh then
    error(
      "consistency manifest not found at "
        .. CASES_JSON
        .. " ("
        .. tostring(err)
        .. "). Run `python tests/consistency/generate_cases.py` to"
        .. " generate it.",
      0
    )
  end
  local content = fh:read("*a")
  fh:close()
  local decoded, decode_err = json.decode(content)
  assert(
    decoded,
    "failed to decode " .. CASES_JSON .. ": " .. tostring(decode_err)
  )
  assert(
    field(decoded, "version", nil) == 1,
    "unsupported consistency manifest version: "
      .. tostring(field(decoded, "version", nil))
  )
  return decoded
end

---@param name string
---@return table
local function find_case(name)
  for _, case in ipairs(field(manifest(), "cases", {})) do
    if field(case, "name", nil) == name then
      return case
    end
  end
  error("consistency case not found in manifest: " .. name, 0)
end

---The RPC surface of the core this binding is linked against, as a set,
---resolved once per run. Cores that predate `BuiltinService.ListMethod`
---answer with an empty list or raise; either way `new_core` cases are skipped
---rather than failed.
---@return table<string, boolean>
local available_methods
local function methods()
  if available_methods then
    return available_methods
  end
  local set = {}
  local ok, result = pcall(api.list_method, api, {})
  if ok then
    for _, name in ipairs(field(result, "method_name_list", {})) do
      set[name] = true
    end
  end
  available_methods = set
  return available_methods
end

---Build `ParseProgramArgs` from the manifest. Path entries are pinned
---repo-relative by `generate_cases.py`; they are resolved against the
---repository root while absolute entries are kept as-is.
---@param node table
---@return table
local function parse_args(node)
  local args = {}
  local paths = {}
  for _, path in ipairs(field(node, "paths", {})) do
    if pl_path.isabs(path) then
      paths[#paths + 1] = path
    else
      paths[#paths + 1] = pl_path.join(REPO_ROOT, path)
    end
  end
  if #paths > 0 then
    args.paths = paths
  end
  local sources = field(node, "sources", nil)
  if sources then
    args.sources = sources
  end
  local external_pkgs = field(node, "external_pkgs", nil)
  if external_pkgs then
    args.external_pkgs = external_pkgs
  end
  return args
end

---Build `ExecProgramArgs` from the manifest. The manifest spells out every
---proto3 field, but the unset ones carry their proto defaults, so only the
---fields that actually drive the case are forwarded.
---@param node table
---@return table
local function exec_args(node)
  local args = {}
  for _, key in ipairs({
    "work_dir",
    "k_filename_list",
    "k_code_list",
    "overrides",
    "disable_yaml_result",
    "print_override_ast",
    "strict_range_check",
    "disable_none",
    "sort_keys",
    "include_schema_type_path",
    "compile_only",
    "show_hidden",
    "path_selector",
    "fast_eval",
    "error_format",
    "format",
    "emit_attribute_metadata",
    "verbose",
    "debug",
  }) do
    local v = field(node, key, nil)
    if v ~= nil and v ~= "" then
      args[key] = v
    end
  end
  -- `args` is a `repeated Argument`, not a `repeated string`.
  local arguments = {}
  for _, spec in ipairs(field(node, "args", {})) do
    local name, value = spec:match("^([^=]*)=(.*)$")
    if name then
      arguments[#arguments + 1] = { name = name, value = value }
    end
  end
  if #arguments > 0 then
    args.args = arguments
  end
  local external_pkgs = field(node, "external_pkgs", nil)
  if external_pkgs and #external_pkgs > 0 then
    args.external_pkgs = external_pkgs
  end
  return args
end

---@return table
local function validate_args(node)
  local args = {}
  for _, key in ipairs({
    "code",
    "data",
    "datafile",
    "file",
    "schema",
    "attribute_name",
    "format",
  }) do
    local v = field(node, key, nil)
    if v ~= nil and v ~= "" then
      args[key] = v
    end
  end
  local external_pkgs = field(node, "external_pkgs", nil)
  if external_pkgs and #external_pkgs > 0 then
    args.external_pkgs = external_pkgs
  end
  return args
end

---The manifest spells `TestCaseInfo.duration` as a decimal string because JSON
---numbers cannot hold a `uint64` microsecond count portably.
---@param value any
---@return integer
local function uint64(value)
  if type(value) == "string" then
    return tonumber(value, 10) or 0
  end
  return value or 0
end

---@param node table
---@return table
local function test_result(node)
  local info = {}
  for _, entry in ipairs(field(node, "info", {})) do
    info[#info + 1] = {
      name = field(entry, "name", ""),
      error = field(entry, "error", ""),
      duration = uint64(field(entry, "duration", 0)),
      log_message = field(entry, "log_message", ""),
    }
  end
  return { info = info }
end

---@return table<string, function> dispatch
local function dispatch()
  return {
    ["KclService.Ping"] = function(case)
      return api:ping({ value = field(case.args, "value", "") })
    end,
    ["KclService.ExecProgram"] = function(case)
      return api:exec_program(exec_args(case.args))
    end,
    ["KclService.FormatCode"] = function(case)
      return api:format_code({ source = field(case.args, "source", "") })
    end,
    ["KclService.ValidateCode"] = function(case)
      return api:validate_code(validate_args(case.args))
    end,
    ["KclService.FormatTestReport"] = function(case)
      return api:format_test_report({
        result = test_result(field(case.args, "result", {})),
      })
    end,
    ["KclService.GenerateToml"] = function(case)
      return api:generate_toml({
        exec_args = exec_args(field(case.args, "exec_args", {})),
        sort_keys = field(case.args, "sort_keys", false),
      })
    end,
    ["KclService.GenerateKcl"] = function(case)
      return api:generate_kcl({
        source = field(case.args, "source", ""),
        filename = field(case.args, "filename", ""),
        format = field(case.args, "format", ""),
      })
    end,
    ["KclService.GenerateOpenAPI"] = function(case)
      return api:generate_openapi({
        parse_args = parse_args(field(case.args, "parse_args", {})),
        version = field(case.args, "version", ""),
      })
    end,
    ["KclService.GenerateProto"] = function(case)
      return api:generate_proto({
        parse_args = parse_args(field(case.args, "parse_args", {})),
        package = field(case.args, "package", ""),
      })
    end,
    ["KclService.GenerateDoc"] = function(case)
      return api:generate_doc({
        parse_args = parse_args(field(case.args, "parse_args", {})),
        format = field(case.args, "format", ""),
      })
    end,
  }
end

---Run one manifest case: dispatch on `rpc`, then compare every field that
---`expect` actually mentions. Unknown RPCs are a hard failure, a missing RPC
---on an old core is a skip.
---@param name string
local function run_case(name)
  local case = find_case(name)
  local rpc = field(case, "rpc", "")
  local call = dispatch()[rpc]
  assert(call, "no runner support for rpc " .. tostring(rpc))

  if field(case, "new_core", false) and not methods()[rpc] then
    pending("core does not list " .. rpc .. " (old core)")
    return
  end

  local result = call(case)
  local expect = field(case, "expect", {})
  -- Compare exactly the fields the manifest pins down, sorted so that a
  -- multi-field mismatch always reports the same one first.
  local keys = {}
  for key in pairs(expect) do
    keys[#keys + 1] = key
  end
  table.sort(keys)
  assert.is_true(#keys > 0, "consistency case `" .. name .. "` pins no fields")
  for _, key in ipairs(keys) do
    local expected, actual
    if key == "success" then
      -- proto3 `bool`; everything else the manifest pins is a string.
      expected = expect[key] == true
      actual = result[key] == true
    else
      expected = expect[key]
      actual = result[key] or ""
    end
    assert.are.equal(
      expected,
      actual,
      string.format(
        "consistency case `%s` field `%s` mismatch\n"
          .. "expected: %s\nactual:   %s",
        name,
        key,
        tostring(expected),
        tostring(actual)
      )
    )
  end
end

describe("consistency", function()
  local case_names = {
    "ping",
    "exec_program_basic",
    "exec_program_overrides",
    "format_code",
    "validate_code_ok",
    "validate_code_invalid",
    "generate_kcl_json",
    "generate_kcl_yaml",
    "generate_toml",
    "format_test_report",
    "generate_openapi_v3",
    "generate_proto",
    "generate_doc_md",
  }

  it("covers every case in the manifest", function()
    local names = {}
    for _, case in ipairs(field(manifest(), "cases", {})) do
      names[case.name] = true
    end
    for _, name in ipairs(case_names) do
      assert.is_true(names[name], "manifest is missing case `" .. name .. "`")
    end
  end)

  for _, name in ipairs(case_names) do
    it(name, function()
      run_case(name)
    end)
  end
end)
