<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * Constructors for every node class, the reference form being
 * kotlin/src/main/kotlin/com/kcl/ast/AstBuild.kt: one factory per node
 * type, and the default for each parameter is the value the Rust parser
 * itself produces for that field — a `Vec<T>` defaults to an empty list
 * and is never `null`, an `Option<T>` defaults to `null`, a `String`
 * written unconditionally defaults to `''`. Building an AST node never
 * makes the caller type an empty collection at every level of the tree.
 */
final class AstBuild
{
    private function __construct()
    {
    }

    /**
     * Wrap a payload in a `NodeRef` — the shape the wire carries. The five
     * position keys are flattened onto the wrapper beside `node`; there is no
     * `pos` key on the wire.
     */
    public static function nodeRef(
        mixed $node = null,
        string $filename = '',
        int $line = 1,
        int $column = 1,
        ?int $endLine = null,
        ?int $endColumn = null,
    ): NodeRef {
        return new NodeRef($node, $filename, $line, $column, $endLine ?? $line, $endColumn ?? $column);
    }

    /**
     * A wrapper that is present but holds nothing — Rust's `Node<T>`,
     * whose `node` field is not an `Option`, so serde writes
     * `"node": null` rather than dropping the key.
     */
    public static function emptyNodeRef(
        string $filename = '',
        int $line = 1,
        int $column = 1,
        ?int $endLine = null,
        ?int $endColumn = null,
    ): NodeRef {
        return new NodeRef(null, $filename, $line, $column, $endLine ?? $line, $endColumn ?? $column);
    }

    /**
     * One segment of a dotted name, wrapped. `nameRef('pkg')`
     * is the `NodeRef<string>` the `Identifier.names` list holds.
     */
    public static function nameRef(
        string $name,
        string $filename = '',
        int $line = 1,
        int $column = 1,
        ?int $endLine = null,
        ?int $endColumn = null,
    ): NodeRef {
        return self::nodeRef($name, $filename, $line, $column, $endLine, $endColumn);
    }

    /**
     * A parameter list — ``lambda x: int = 1, y: int = 1 { ... }``, or a
     * schema's generics.
     *
     * ``defaults`` and ``ty_list`` are ``Vec<Option<NodeRef<...>>>`` and are
     * index-aligned with ``args``: slot *i* describes parameter *i*. The nulls
     * occupy their slots and are kept, because dropping one would shift every
     * later annotation onto the wrong parameter.
     */
    public static function arguments(
        /** @var list<NodeRef<Identifier>> */
        array $args = [],
        /** @var list<NodeRef<Expr>|null> */
        array $defaults = [],
        /** @var list<NodeRef<Type>|null> */
        array $tyList = [],
    ): Arguments {
        return new Arguments(args: $args, defaults: $defaults, tyList: $tyList);
    }

    /**
     * AssertStmt represents an assert statement, e.g. ```kcl assert True if
     * condition, "Assert failed message" ```
     */
    public static function assertStmt(
        /** @var NodeRef<Expr> */
        ?NodeRef $test = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $ifCond = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $msg = null,
    ): AssertStmt {
        return new AssertStmt(test: $test, ifCond: $ifCond, msg: $msg);
    }

    /**
     * AssignStmt represents an assignment, e.g. ```kcl a: int = 1 a["key"] =
     * "value" a.b["key"].c = "value" a[0] = 1 ``` Valid left-hand side of an
     * assignment expressions: - Expr::Identifier a - Expr::Subscript  e.g.
     * `a[0]`, `b["k"]`
     */
    public static function assignStmt(
        /** @var list<NodeRef<Target>> */
        array $targets = [],
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var NodeRef<Type> */
        ?NodeRef $ty = null,
    ): AssignStmt {
        return new AssignStmt(targets: $targets, value: $value, ty: $ty);
    }

    /**
     * AugAssignStmt represents an argument assignment, e.g. ```kcl a += 1 a[0]
     * += 2 ```
     */
    public static function augAssignStmt(
        /** @var NodeRef<Target> */
        ?NodeRef $target = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var ?string */
        ?string $op = null,
    ): AugAssignStmt {
        return new AugAssignStmt(target: $target, value: $value, op: $op);
    }

    /**
     * BinaryExpr, e.g. ```kcl 1 + 1 3 - 2 5 / 2 a is None ```
     */
    public static function binaryExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $left = null,
        /** @var ?string */
        ?string $op = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $right = null,
    ): BinaryExpr {
        return new BinaryExpr(left: $left, op: $op, right: $right);
    }

    /**
     * ``f(a, b=1)``.
     *
     * Also the shape of a decorator — ``SchemaStmt.decorators`` is
     * ``Vec<NodeRef<CallExpr>>``, so ``@deprecated(strict=True)`` arrives as a
     * bare ``{func, args, keywords}`` with no tag.
     */
    public static function callExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $func = null,
        /** @var list<NodeRef<Expr>> */
        array $args = [],
        /** @var list<NodeRef<Keyword>> */
        array $keywords = [],
    ): CallExpr {
        return new CallExpr(func: $func, args: $args, keywords: $keywords);
    }

    /**
     * ``len(attr) > 3 if attr, "message"``.
     *
     * A plain struct, not a tagged ``Expr``: ``SchemaStmt.checks`` is
     * ``Vec<NodeRef<CheckExpr>>`` and every element is a bare ``{test,
     * if_cond, msg}`` object. ``Expr::Check`` is the same struct with a
     * ``"type"`` key.
     */
    public static function checkExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $test = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $ifCond = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $msg = null,
    ): CheckExpr {
        return new CheckExpr(test: $test, ifCond: $ifCond, msg: $msg);
    }

    /**
     * A line/block comment captured during parsing.
     *
     * A plain struct with a *single* `String` field in Rust, so serde nests it
     * as ``{"node": {"text": "…"}, "line": 1, …}`` — the object under `node`
     * is an object, not the bare text. Reading it as the text itself yields
     * `""` for every comment in the file without raising, which is why the
     * round-trip looks fine and the content does not.
     */
    public static function comment(
        /** @var string */
        string $text = '',
    ): Comment {
        return new Comment(text: $text);
    }

    /**
     * One ``for x in y if z`` leg of a comprehension.
     *
     * A plain struct: ``ListComp.generators`` and ``DictComp.generators`` are
     * ``Vec<NodeRef<CompClause>>``, so there is no ``"type"`` key to dispatch
     * on.
     */
    public static function compClause(
        /** @var list<NodeRef<Identifier>> */
        array $targets = [],
        /** @var NodeRef<Expr> */
        ?NodeRef $iter = null,
        /** @var list<NodeRef<Expr>> */
        array $ifs = [],
    ): CompClause {
        return new CompClause(targets: $targets, iter: $iter, ifs: $ifs);
    }

    /**
     * Compare, e.g. ```kcl 0 < a < 10 b is not None c != d ```
     */
    public static function compare(
        /** @var NodeRef<Expr> */
        ?NodeRef $left = null,
        /** @var list<CmpOp> */
        array $ops = [],
        /** @var list<NodeRef<Expr>> */
        array $comparators = [],
    ): Compare {
        return new Compare(left: $left, ops: $ops, comparators: $comparators);
    }

    /**
     * One ``key = value`` / ``key: value`` / ``key += value`` in a config.
     *
     * ``is_shorthand`` is a real ``bool`` — the ``{name}`` form — and the wire
     * omits the key when it is false, so it is read as ``False`` rather than
     * as absent. A ``DictComp`` has exactly one ``entry: ConfigEntry``, not
     * separate key/value/entry_key fields.
     */
    public static function configEntry(
        /** @var NodeRef<Expr> */
        ?NodeRef $key = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var ?string */
        ?string $operation = null,
        /** @var bool */
        bool $isShorthand = false,
    ): ConfigEntry {
        return new ConfigEntry(key: $key, value: $value, operation: $operation, isShorthand: $isShorthand);
    }

    /**
     * ConfigExpr, e.g. ```kcl { attr1 = 1 attr2 = 2 } ```
     */
    public static function configExpr(
        /** @var list<NodeRef<ConfigEntry>> */
        array $items = [],
    ): ConfigExpr {
        return new ConfigExpr(items: $items);
    }

    /**
     * ConfigIfEntryExpr, e.g. ```kcl { k1 = 1 if condition: k2 = 2 } ```
     */
    public static function configIfEntryExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $ifCond = null,
        /** @var list<NodeRef<ConfigEntry>> */
        array $items = [],
        /** @var NodeRef<Expr> */
        ?NodeRef $orelse = null,
    ): ConfigIfEntryExpr {
        return new ConfigIfEntryExpr(ifCond: $ifCond, items: $items, orelse: $orelse);
    }

    /**
     * DictComp, e.g. ```kcl {k: v + 1 for k, v in {k1 = 1, k2 = 2}} ```
     */
    public static function dictComp(
        /** @var ?ConfigEntry */
        ?ConfigEntry $entry = null,
        /** @var list<NodeRef<CompClause>> */
        array $generators = [],
    ): DictComp {
        return new DictComp(entry: $entry, generators: $generators);
    }

    /**
     * ``{K: V}``. Both sides are ``Option<NodeRef<Type>>`` for the same reason
     * ``ListType.inner_type`` is optional.
     */
    public static function dictType(
        /** @var NodeRef<Type> */
        ?NodeRef $keyType = null,
        /** @var NodeRef<Type> */
        ?NodeRef $valueType = null,
    ): DictType {
        return new DictType(keyType: $keyType, valueType: $valueType);
    }

    /**
     * ExprStmt represents a expression statement, e.g. ```kcl 1 """A long
     * string""" ```
     */
    public static function exprStmt(
        /** @var list<NodeRef<Expr>> */
        array $exprs = [],
    ): ExprStmt {
        return new ExprStmt(exprs: $exprs);
    }

    /**
     * FormattedValue, e.g. var1 and var2  in the string interpolation "${var1}
     * abc ${var2}"
     */
    public static function formattedValue(
        /** @var bool */
        bool $isLongString = false,
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var ?string */
        ?string $formatSpec = null,
    ): FormattedValue {
        return new FormattedValue(isLongString: $isLongString, value: $value, formatSpec: $formatSpec);
    }

    /**
     * ``(T1, T2) -> R``.
     *
     * ``params_ty`` is an ``Option<Vec<NodeRef<Type>>>``, which is two states
     * on the wire and not three: the parser turns an empty parameter list into
     * ``None`` (``crates/parser/src/parser/ty.rs``), so ``Some([])`` never
     * arrives and the reader treats a missing list and an empty one the same
     * way rather than inventing a distinction the wire cannot carry. It is
     * kept as ``Optional`` rather than defaulted to ``[]`` because ``ret_ty``
     * alone is a real ``() -> R`` and the two must stay distinguishable.
     */
    public static function functionType(
        /** @var list<NodeRef<Type>> */
        array $paramsTy = [],
        /** @var NodeRef<Type> */
        ?NodeRef $retTy = null,
    ): FunctionType {
        return new FunctionType(paramsTy: $paramsTy, retTy: $retTy);
    }

    /**
     * ``a`` / ``pkg.a`` / ``_c``.
     *
     * Rust declares ``pub struct Identifier { names, pkgpath, ctx }`` — a
     * plain struct, so the same payload appears untagged under
     * ``Keyword.arg``, ``QuantExpr.variables``, ``Arguments.args``,
     * ``SelectorExpr.attr``, ``Type::Named`` and ``TypeAliasStmt.type_name``,
     * and tagged as ``Expr::Identifier``. One class covers both.
     */
    public static function identifier(
        /** @var list<NodeRef<string>> */
        array $names = [],
        /** @var string */
        string $pkgpath = '',
        /** @var ?string */
        ?string $ctx = null,
    ): Identifier {
        return new Identifier(names: $names, pkgpath: $pkgpath, ctx: $ctx);
    }

    /**
     * IfExpr, e.g. ```kcl 1 if condition else 2 ```
     */
    public static function ifExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $body = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $cond = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $orelse = null,
    ): IfExpr {
        return new IfExpr(body: $body, cond: $cond, orelse: $orelse);
    }

    /**
     * IfStmt, e.g. ```kcl if condition1: if condition2: a = 1 elif condition3:
     * b = 2 else: c = 3 ```
     */
    public static function ifStmt(
        /** @var list<NodeRef<Stmt>> */
        array $body = [],
        /** @var NodeRef<Expr> */
        ?NodeRef $cond = null,
        /** @var list<NodeRef<Stmt>> */
        array $orelse = [],
    ): IfStmt {
        return new IfStmt(body: $body, cond: $cond, orelse: $orelse);
    }

    /**
     * ImportStmt, e.g. ```kcl import pkg as pkg_alias ```
     */
    public static function importStmt(
        /** @var NodeRef<string> */
        ?NodeRef $path = null,
        /** @var string */
        string $rawpath = '',
        /** @var string */
        string $name = '',
        /** @var NodeRef<string> */
        ?NodeRef $asname = null,
        /** @var string */
        string $pkgName = '',
    ): ImportStmt {
        return new ImportStmt(path: $path, rawpath: $rawpath, name: $name, asname: $asname, pkgName: $pkgName);
    }

    public static function intLiteralType(
        /** @var int */
        int $value = 0,
        /** @var ?string */
        ?string $suffix = null,
    ): IntLiteralType {
        return new IntLiteralType(value: $value, suffix: $suffix);
    }

    /**
     * JoinedString, e.g. abc in the string interpolation "${var1} abc ${var2}"
     */
    public static function joinedString(
        /** @var bool */
        bool $isLongString = false,
        /** @var list<NodeRef<Expr>> */
        array $values = [],
        /** @var string */
        string $rawValue = '',
    ): JoinedString {
        return new JoinedString(isLongString: $isLongString, values: $values, rawValue: $rawValue);
    }

    /**
     * ``arg=value`` in a call or a schema.
     *
     * A plain struct: ``CallExpr.keywords`` is ``Vec<NodeRef<Keyword>>``, so
     * an element arrives untagged, and ``Expr::Keyword`` is the same struct
     * with a ``"type"`` key added.
     */
    public static function keyword(
        /** @var NodeRef<Identifier> */
        ?NodeRef $arg = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
    ): Keyword {
        return new Keyword(arg: $arg, value: $value);
    }

    /**
     * LambdaExpr, e.g. ```kcl lambda x, y { z = 2 * x z + y } ```
     */
    public static function lambdaExpr(
        /** @var NodeRef<Arguments> */
        ?NodeRef $args = null,
        /** @var list<NodeRef<Stmt>> */
        array $body = [],
        /** @var NodeRef<Type> */
        ?NodeRef $returnTy = null,
    ): LambdaExpr {
        return new LambdaExpr(args: $args, body: $body, returnTy: $returnTy);
    }

    /**
     * ListComp, e.g. ```kcl [x ** 2 for x in [1, 2, 3]] ```
     */
    public static function listComp(
        /** @var NodeRef<Expr> */
        ?NodeRef $elt = null,
        /** @var list<NodeRef<CompClause>> */
        array $generators = [],
    ): ListComp {
        return new ListComp(elt: $elt, generators: $generators);
    }

    /**
     * ListExpr, e.g. ```kcl [1, 2, 3] ```
     */
    public static function listExpr(
        /** @var list<NodeRef<Expr>> */
        array $elts = [],
        /** @var ?string */
        ?string $ctx = null,
    ): ListExpr {
        return new ListExpr(elts: $elts, ctx: $ctx);
    }

    /**
     * ListIfItemExpr, e.g. ```kcl [1, if condition: 2, 3] ```
     */
    public static function listIfItemExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $ifCond = null,
        /** @var list<NodeRef<Expr>> */
        array $exprs = [],
        /** @var NodeRef<Expr> */
        ?NodeRef $orelse = null,
    ): ListIfItemExpr {
        return new ListIfItemExpr(ifCond: $ifCond, exprs: $exprs, orelse: $orelse);
    }

    /**
     * ``[T]``. ``inner_type`` is an ``Option<NodeRef<Type>>``, and an absent
     * one means the list is unparameterised (``list``), not empty.
     */
    public static function listType(
        /** @var NodeRef<Type> */
        ?NodeRef $innerType = null,
    ): ListType {
        return new ListType(innerType: $innerType);
    }

    /**
     * The parser's error-recovery placeholder. It has no fields, so the wire
     * is ``{"type": "Missing"}`` and nothing else.
     */
    public static function missingExpr(): MissingExpr
    {
        return new MissingExpr();
    }

    /**
     * Module is an abstract syntax tree for a single KCL file.
     */
    public static function module(
        /** @var string */
        string $filename = '',
        /** @var NodeRef<string> */
        ?NodeRef $doc = null,
        /** @var list<NodeRef<Stmt>> */
        array $body = [],
        /** @var list<NodeRef<Comment>> */
        array $comments = [],
    ): Module {
        return new Module(filename: $filename, doc: $doc, body: $body, comments: $comments);
    }

    public static function nameConstantLit(
        /** @var ?string */
        ?string $value = null,
    ): NameConstantLit {
        return new NameConstantLit(value: $value);
    }

    /**
     * NumberLit, e.g. ```kcl 1m 1K 1Mi ```
     */
    public static function numberLit(
        /** @var ?string */
        ?string $binarySuffix = null,
        /** @var ?NumberLitValue */
        ?NumberLitValue $value = null,
    ): NumberLit {
        return new NumberLit(binarySuffix: $binarySuffix, value: $value);
    }

    /**
     * ParenExpr, e.g. ```kcl 1 + (2 - 3) ```
     */
    public static function parenExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $expr = null,
    ): ParenExpr {
        return new ParenExpr(expr: $expr);
    }

    /**
     * QuantExpr, <op> <variables> in <target> {<test> <if_cond>}  e.g. ```kcl
     * all x in collection {x > 0} any y in collection {y < 0} map x in
     * collection {x + 1} filter x in collection {x > 1} ```
     */
    public static function quantExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $target = null,
        /** @var list<NodeRef<Identifier>> */
        array $variables = [],
        /** @var ?string */
        ?string $op = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $test = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $ifCond = null,
        /** @var ?string */
        ?string $ctx = null,
    ): QuantExpr {
        return new QuantExpr(target: $target, variables: $variables, op: $op, test: $test, ifCond: $ifCond, ctx: $ctx);
    }

    /**
     * RuleStmt, e.g. ```kcl rule RuleExample: a > 1 b < 0 ```
     */
    public static function ruleStmt(
        /** @var NodeRef<string> */
        ?NodeRef $doc = null,
        /** @var NodeRef<string> */
        ?NodeRef $name = null,
        /** @var list<NodeRef<Identifier>> */
        array $parentRules = [],
        /** @var list<NodeRef<CallExpr>> */
        array $decorators = [],
        /** @var list<NodeRef<CheckExpr>> */
        array $checks = [],
        /** @var NodeRef<Arguments> */
        ?NodeRef $args = null,
        /** @var NodeRef<Identifier> */
        ?NodeRef $forHostName = null,
    ): RuleStmt {
        return new RuleStmt(doc: $doc, name: $name, parentRules: $parentRules, decorators: $decorators, checks: $checks, args: $args, forHostName: $forHostName);
    }

    /**
     * SchemaAttr, e.g. ```kcl schema SchemaAttrExample: x: int y: str ```
     */
    public static function schemaAttr(
        /** @var string */
        string $doc = '',
        /** @var NodeRef<string> */
        ?NodeRef $name = null,
        /** @var ?string */
        ?string $op = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var bool */
        bool $isOptional = false,
        /** @var list<NodeRef<CallExpr>> */
        array $decorators = [],
        /** @var NodeRef<Type> */
        ?NodeRef $ty = null,
    ): SchemaAttr {
        return new SchemaAttr(doc: $doc, name: $name, op: $op, value: $value, isOptional: $isOptional, decorators: $decorators, ty: $ty);
    }

    /**
     * A schema *expression*: ``Person { name = "x" }``.
     *
     * Reached two ways: as ``Expr::Schema`` (tagged) and as
     * ``UnificationStmt.value`` (``NodeRef<SchemaExpr>``, untagged), which is
     * why it is declared once and aliased as ``SchemaConfig``.
     */
    public static function schemaExpr(
        /** @var NodeRef<Identifier> */
        ?NodeRef $name = null,
        /** @var list<NodeRef<Expr>> */
        array $args = [],
        /** @var list<NodeRef<Keyword>> */
        array $kwargs = [],
        /** @var NodeRef<Expr> */
        ?NodeRef $config = null,
    ): SchemaExpr {
        return new SchemaExpr(name: $name, args: $args, kwargs: $kwargs, config: $config);
    }

    /**
     * The ``[k: str]: int`` statement in a schema body.
     *
     * A statement, not part of the ``schema`` header: ``schema Bag[k: str]``
     * is a generic schema whose ``args`` is an ``Arguments``.
     */
    public static function schemaIndexSignature(
        /** @var NodeRef<string> */
        ?NodeRef $keyName = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var bool */
        bool $anyOther = false,
        /** @var NodeRef<Type> */
        ?NodeRef $keyTy = null,
        /** @var NodeRef<Type> */
        ?NodeRef $valueTy = null,
    ): SchemaIndexSignature {
        return new SchemaIndexSignature(keyName: $keyName, value: $value, anyOther: $anyOther, keyTy: $keyTy, valueTy: $valueTy);
    }

    /**
     * SchemaStmt, e.g. ```kcl schema BaseSchema:  schema
     * SchemaExample(BaseSchema)[arg: str]: """Schema documents""" attr?: str =
     * arg check: len(attr) > 3 if attr, "Check failed message"  mixin
     * MixinExample for ProtocolExample: attr: int  protocol ProtocolExample:
     * attr: int ```
     */
    public static function schemaStmt(
        /** @var NodeRef<string> */
        ?NodeRef $doc = null,
        /** @var NodeRef<string> */
        ?NodeRef $name = null,
        /** @var NodeRef<Identifier> */
        ?NodeRef $parentName = null,
        /** @var NodeRef<Identifier> */
        ?NodeRef $forHostName = null,
        /** @var bool */
        bool $isMixin = false,
        /** @var bool */
        bool $isProtocol = false,
        /** @var NodeRef<Arguments> */
        ?NodeRef $args = null,
        /** @var list<NodeRef<Identifier>> */
        array $mixins = [],
        /** @var list<NodeRef<Stmt>> */
        array $body = [],
        /** @var list<NodeRef<CallExpr>> */
        array $decorators = [],
        /** @var list<NodeRef<CheckExpr>> */
        array $checks = [],
        /** @var NodeRef<SchemaIndexSignature> */
        ?NodeRef $indexSignature = null,
    ): SchemaStmt {
        return new SchemaStmt(doc: $doc, name: $name, parentName: $parentName, forHostName: $forHostName, isMixin: $isMixin, isProtocol: $isProtocol, args: $args, mixins: $mixins, body: $body, decorators: $decorators, checks: $checks, indexSignature: $indexSignature);
    }

    /**
     * SelectorExpr, e.g. ```kcl x.y x?.y ```
     */
    public static function selectorExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var NodeRef<Identifier> */
        ?NodeRef $attr = null,
        /** @var ?string */
        ?string $ctx = null,
        /** @var bool */
        bool $hasQuestion = false,
    ): SelectorExpr {
        return new SelectorExpr(value: $value, attr: $attr, ctx: $ctx, hasQuestion: $hasQuestion);
    }

    /**
     * StarredExpr, e.g. ```kcl [1, 2, *[3, 4]] ```
     */
    public static function starredExpr(
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var ?string */
        ?string $ctx = null,
    ): StarredExpr {
        return new StarredExpr(value: $value, ctx: $ctx);
    }

    /**
     * StringLit, e.g. ```kcl "string literal" """long string literal""" ```
     */
    public static function stringLit(
        /** @var bool */
        bool $isLongString = false,
        /** @var string */
        string $rawValue = '',
        /** @var string */
        string $value = '',
    ): StringLit {
        return new StringLit(isLongString: $isLongString, rawValue: $rawValue, value: $value);
    }

    /**
     * Subscript, e.g. ```kcl a[0] b["k"] c?[1] ```
     */
    public static function subscript(
        /** @var NodeRef<Expr> */
        ?NodeRef $value = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $index = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $lower = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $upper = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $step = null,
        /** @var ?string */
        ?string $ctx = null,
        /** @var bool */
        bool $hasQuestion = false,
    ): Subscript {
        return new Subscript(value: $value, index: $index, lower: $lower, upper: $upper, step: $step, ctx: $ctx, hasQuestion: $hasQuestion);
    }

    /**
     * The left-hand side of an assignment: ``a`` / ``a.b.c`` / ``a[0].b``.
     *
     * ``Target`` is both a plain struct (under ``AssignStmt.targets``) and the
     * ``Expr::Target`` variant, so it decodes from both shapes.
     */
    public static function target(
        /** @var NodeRef<string> */
        ?NodeRef $name = null,
        /** @var list<MemberOrIndex> */
        array $paths = [],
        /** @var string */
        string $pkgpath = '',
    ): Target {
        return new Target(name: $name, paths: $paths, pkgpath: $pkgpath);
    }

    /**
     * TypeAliasStmt represents a type alias statement, e.g. ```kcl type
     * StrOrInt = str | int ```
     */
    public static function typeAliasStmt(
        /** @var NodeRef<Identifier> */
        ?NodeRef $typeName = null,
        /** @var NodeRef<string> */
        ?NodeRef $typeValue = null,
        /** @var NodeRef<Type> */
        ?NodeRef $ty = null,
    ): TypeAliasStmt {
        return new TypeAliasStmt(typeName: $typeName, typeValue: $typeValue, ty: $ty);
    }

    /**
     * UnaryExpr, e.g. ```kcl +1 -2 ~3 not True ```
     */
    public static function unaryExpr(
        /** @var ?string */
        ?string $op = null,
        /** @var NodeRef<Expr> */
        ?NodeRef $operand = null,
    ): UnaryExpr {
        return new UnaryExpr(op: $op, operand: $operand);
    }

    /**
     * UnificationStmt represents a declare statement with the union operator,
     * e.g. ```kcl data: ASchema {} ```
     */
    public static function unificationStmt(
        /** @var NodeRef<Identifier> */
        ?NodeRef $target = null,
        /** @var NodeRef<SchemaExpr> */
        ?NodeRef $value = null,
    ): UnificationStmt {
        return new UnificationStmt(target: $target, value: $value);
    }

    /**
     * ``T1 | T2 | ...``. The Rust field is ``type_elements``, not ``types``;
     * the Python binding keeps the Rust spelling and the TypeScript one
     * renames it to ``types``. Both are asserted by their contract test, so
     * both are the existing names rather than a third one.
     */
    public static function unionType(
        /** @var list<NodeRef<Type>> */
        array $typeElements = [],
    ): UnionType {
        return new UnionType(typeElements: $typeElements);
    }

    /**
     * ``a.b`` / ``b[0]`` inside a ``Target``'s path list.
     *
     * ``MemberOrIndex`` is its own adjacently-tagged enum (``tag = "type",
     * content = "value"``) and, unusually for this crate, the payload is a
     * ``NodeRef`` — so the value keeps its own position::
     *
     * {"type": "Member", "value": {"node": "b", "line": 3}} {"type": "Index",
     * "value": {"node": {"type": "NumberLit", ...}}}
     */
    public static function memberOrIndex(
        /** @var string */
        string $kind = '',
        /** @var NodeRef<string>|NodeRef<Expr> */
        ?NodeRef $node = null,
    ): MemberOrIndex {
        return new MemberOrIndex(kind: $kind, node: $node);
    }

    /**
     * The number inside a ``NumberLit``.
     *
     * ``NumberLitValue`` is its own ``tag + content`` enum, so the wire is
     * ``{"type": "Int", "value": 1}`` — an object, not a bare number.
     */
    public static function numberLitValue(
        /** @var string */
        string $kind = '',
        /** @var mixed */
        mixed $value = null,
    ): NumberLitValue {
        return new NumberLitValue(kind: $kind, value: $value);
    }

    public static function anyType(): AnyType
    {
        return new AnyType();
    }

    /**
     * ``a`` / ``pkg.a`` / ``_c``.
     *
     * Rust declares ``pub struct Identifier { names, pkgpath, ctx }`` — a
     * plain struct, so the same payload appears untagged under
     * ``Keyword.arg``, ``QuantExpr.variables``, ``Arguments.args``,
     * ``SelectorExpr.attr``, ``Type::Named`` and ``TypeAliasStmt.type_name``,
     * and tagged as ``Expr::Identifier``. One class covers both.
     */
    public static function namedType(
        /** @var ?Identifier */
        ?Identifier $identifier = null,
    ): NamedType {
        return new NamedType(identifier: $identifier);
    }

    /**
     * ``Int`` / ``Str`` / ``Float`` / ``Bool``.
     *
     * ``BasicType`` is a *fieldless* enum in Rust, so there is no struct to
     * nest it in: the payload is the bare JSON string and the wire is
     * ``{"type":"Basic","value":"Int"}`` — never ``{"type":"Int"}``. The four
     * strings are read from the enum's own variants rather than listed here,
     * so a fifth one upstream shows up here as a diff.
     *
     * They are exposed as a plain ``str`` rather than as an ``Enum`` for the
     * same reason the DTO fields hold raw strings: a value this build does not
     * recognise must round-trip, not raise.
     */
    public static function basicType(
        /** @var string */
        string $name = '',
    ): BasicType {
        return new BasicType(name: $name);
    }

    /**
     * ``1``, ``"a"``, ``true`` in a type position.
     *
     * ``LiteralType`` is *itself* adjacently tagged, so the payload is doubly
     * nested: ``{"type":"Literal","value":{"type":"Int","value":{"value":1,
     * "suffix":null}}}``. Its four variants do not share a field set — ``Int``
     * inlines the ``IntLiteralType`` struct while the other three are bare
     * scalars — so the inner document is kept whole and ``inner_tag`` records
     * which kind it was.
     */
    public static function literalType(
        /** @var array<string, mixed> */
        array $value = [],
    ): LiteralType {
        return new LiteralType(value: $value);
    }
}
