<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * The variants of `AugOp`. A Rust enum with no `#[serde]` attribute at
 * all, so the value on the wire is a bare JSON string — `AugOp::Assign` is
 * "Assign", not `{"Assign": null}` — and these constants are the whole
 * vocabulary.
 */
final class AugOp
{
    public const Assign = 'Assign';
    public const Add = 'Add';
    public const Sub = 'Sub';
    public const Mul = 'Mul';
    public const Div = 'Div';
    public const Mod = 'Mod';
    public const Pow = 'Pow';
    public const FloorDiv = 'FloorDiv';
    public const LShift = 'LShift';
    public const RShift = 'RShift';
    public const BitXor = 'BitXor';
    public const BitAnd = 'BitAnd';
    public const BitOr = 'BitOr';

    private function __construct()
    {
    }
}
