<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * ``f(a, b=1)``.
 *
 * Also the shape of a decorator — ``SchemaStmt.decorators`` is
 * ``Vec<NodeRef<CallExpr>>``, so ``@deprecated(strict=True)`` arrives as a
 * bare ``{func, args, keywords}`` with no tag.
 */
final class CallExpr extends Expr
{
    public function __construct(
        /** @var NodeRef<Expr> */
        public readonly ?NodeRef $func = null,
        /** @var list<NodeRef<Expr>> */
        public readonly array $args = [],
        /** @var list<NodeRef<Keyword>> */
        public readonly array $keywords = []
    ) {
    }

    /**
     * Decode from this node's wire object. Every key is read
     * through the one `Wire` helper for its shape, which is the
     * only place the four shapes are told apart.
     */
    public static function fromWire(mixed $w): ?self
    {
        if (!is_array($w)) {
            return null;
        }

        return new self(
            func: Wire::nodeRef($w, 'func', 'expr'),
            args: Wire::nodeRefList($w, 'args', 'expr'),
            keywords: Wire::nodeRefList($w, 'keywords', 'keyword')
        );
    }
}
