<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * ``a.b`` / ``b[0]`` inside a ``Target``'s path list.
 *
 * ``MemberOrIndex`` is its own adjacently-tagged enum (``tag = "type",
 * content = "value"``) and, unusually for this crate, the payload is a
 * ``NodeRef`` — so the value keeps its own position::
 *
 * {"type": "Member", "value": {"node": "b", "line": 3}} {"type": "Index",
 * "value": {"node": {"type": "NumberLit", ...}}}
 */
final class MemberOrIndex
{
    public function __construct(
        /** @var string */
        public readonly string $kind = '',
        /** @var NodeRef<string>|NodeRef<Expr> */
        public readonly ?NodeRef $node = null
    ) {
    }

    /**
     * Decode the `kind` plus its payload; the payload's decoder
     * differs per variant, so the tag is read first. Both arms
     * hold a `NodeRef` (`Member` a `NodeRef<string>`, `Index` a
     * `NodeRef<Expr>`), so the wire value is the whole wrapper
     * with its five position keys, not the bare payload.
     */
    public static function fromWire(mixed $w): ?self
    {
        if (!is_array($w)) {
            return null;
        }

        $kind = Wire::str($w, 'type');
        $node = Wire::payloadForKind($kind, $w['value'] ?? null);

        return new self($kind, $node);
    }
}
