<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * The variants of `NumberBinarySuffix`. A Rust enum with no `#[serde]`
 * attribute at all, so the value on the wire is a bare JSON string —
 * `NumberBinarySuffix::n` is "n", not `{"n": null}` — and these constants
 * are the whole vocabulary.
 */
final class NumberBinarySuffix
{
    public const n = 'n';
    public const u = 'u';
    public const m = 'm';
    public const k = 'k';
    public const K = 'K';
    public const M = 'M';
    public const G = 'G';
    public const T = 'T';
    public const P = 'P';
    public const Ki = 'Ki';
    public const Mi = 'Mi';
    public const Gi = 'Gi';
    public const Ti = 'Ti';
    public const Pi = 'Pi';

    private function __construct()
    {
    }
}
