<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * The variants of `QuantOperation`. A Rust enum with no `#[serde]`
 * attribute at all, so the value on the wire is a bare JSON string —
 * `QuantOperation::All` is "All", not `{"All": null}` — and these
 * constants are the whole vocabulary.
 */
final class QuantOperation
{
    public const All = 'All';
    public const Any = 'Any';
    public const Filter = 'Filter';
    public const Map = 'Map';

    private function __construct()
    {
    }
}
