<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * SchemaAttr, e.g. ```kcl schema SchemaAttrExample: x: int y: str ```
 */
final class SchemaAttr extends Stmt
{
    public function __construct(
        /** @var string */
        public readonly string $doc = '',
        /** @var NodeRef<string> */
        public readonly ?NodeRef $name = null,
        /** @var ?string */
        public readonly ?string $op = null,
        /** @var NodeRef<Expr> */
        public readonly ?NodeRef $value = null,
        /** @var bool */
        public readonly bool $isOptional = false,
        /** @var list<NodeRef<CallExpr>> */
        public readonly array $decorators = [],
        /** @var NodeRef<Type> */
        public readonly ?NodeRef $ty = null
    ) {
    }

    /**
     * Decode from this node's wire object. Every key is read
     * through the one `Wire` helper for its shape, which is the
     * only place the four shapes are told apart.
     */
    public static function fromWire(mixed $w): ?self
    {
        if (!is_array($w)) {
            return null;
        }

        return new self(
            doc: Wire::str($w, 'doc'),
            name: Wire::stringNode($w, 'name'),
            op: Wire::optStr($w, 'op'),
            value: Wire::nodeRef($w, 'value', 'expr'),
            isOptional: Wire::bool($w, 'is_optional'),
            decorators: Wire::nodeRefList($w, 'decorators', 'call_expr'),
            ty: Wire::nodeRef($w, 'ty', 'type')
        );
    }
}
