<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * One type variant of the `Type` hierarchy. Decode with the one static
 * `fromWire`; a caller dispatches on the concrete class with `instanceof`.
 */
abstract class Type
{
    /**
     * Read a `Type` off the wire. `type` is the
     * discriminator every variant carries, so the dispatch
     * is a lookup rather than a guess; a tag this build
     * does not know decodes to null rather than to a
     * zero-valued node.
     */
    public static function fromWire(mixed $w): ?Type
    {
        if (!is_array($w)) {
            return null;
        }

        $payload = $w['value'] ?? null;

        return match ($w['type'] ?? null) {
            'Any' => AnyType::fromWire($payload),
            'Named' => NamedType::fromWire($payload),
            'Basic' => BasicType::fromWire($payload),
            'List' => ListType::fromWire($payload),
            'Dict' => DictType::fromWire($payload),
            'Union' => UnionType::fromWire($payload),
            'Literal' => LiteralType::fromWire($payload),
            'Function' => FunctionType::fromWire($payload),
            default => null,
        };
    }
}
