<?php

// Code generated by tools/generate_ast.py from
// kcl-lang/kcl/crates/ast/src/ast.rs (sha256:8b77fdb5564727374c563b95f8ab2a62af42a0d069183c5ee28256dae4b0ee03).
// DO NOT EDIT BY HAND — run `python3 tools/generate_ast.py` and commit the
// result, or `ruby hack/check_generated_ast.rb` will fail.
//
// Every class, field, wire tag and operator below is derived from the Rust
// source. See tools/astgen/emit_php.py for the shapes and why they are so.

declare(strict_types=1);

namespace KclLib\Ast;

/**
 * ``T1 | T2 | ...``. The Rust field is ``type_elements``, not ``types``;
 * the Python binding keeps the Rust spelling and the TypeScript one
 * renames it to ``types``. Both are asserted by their contract test, so
 * both are the existing names rather than a third one.
 */
final class UnionType extends Type
{
    public function __construct(
        /** @var list<NodeRef<Type>> */
        public readonly array $typeElements = []
    ) {
    }

    /**
     * Decode from this node's wire object. Every key is read
     * through the one `Wire` helper for its shape, which is the
     * only place the four shapes are told apart.
     */
    public static function fromWire(mixed $w): ?self
    {
        if (!is_array($w)) {
            return null;
        }

        return new self(
            typeElements: Wire::nodeRefList($w, 'type_elements', 'type')
        );
    }
}
