"""Cross-language consistency runner (python binding).

Executes the hermetic cases from ``tests/consistency/cases.json`` — the
manifest generated by ``tests/consistency/generate_cases.py`` — and asserts
the same golden expectations every other language runner asserts.

Run with the venv that has the locally-built binding:

    source python/venv/bin/activate
    pytest python/tests/consistency_test.py -v

If ``cases.json`` is missing, regenerate it with
``python tests/consistency/generate_cases.py``.
"""

import difflib
import json
from pathlib import Path

import pytest

import kcl_lib.api as api

CASES_JSON = (
    Path(__file__).resolve().parent.parent.parent
    / "tests"
    / "consistency"
    / "cases.json"
)


def _load_cases():
    if not CASES_JSON.exists():
        pytest.fail(
            f"consistency manifest not found: {CASES_JSON}. "
            "Run `python tests/consistency/generate_cases.py` to generate it."
        )
    manifest = json.loads(CASES_JSON.read_text(encoding="utf-8"))
    assert manifest["version"] == 1, f"unsupported manifest version: {manifest['version']}"
    return manifest["cases"]


def _build_args(case):
    rpc = case["rpc"]
    a = case["args"]
    if rpc == "KclService.Ping":
        return api.PingArgs(value=a["value"])
    if rpc == "KclService.ExecProgram":
        return api.ExecProgramArgs(**a)
    if rpc == "KclService.FormatCode":
        return api.FormatCodeArgs(source=a["source"])
    if rpc == "KclService.ValidateCode":
        return api.ValidateCodeArgs(
            code=a["code"], data=a["data"], format=a.get("format", "")
        )
    if rpc == "KclService.GenerateKcl":
        return api.GenerateKclArgs(
            source=a["source"], filename=a["filename"], format=a["format"]
        )
    if rpc == "KclService.GenerateToml":
        return api.GenerateTomlArgs(
            exec_args=api.ExecProgramArgs(**a["exec_args"]),
            sort_keys=a.get("sort_keys", False),
        )
    if rpc == "KclService.FormatTestReport":
        return api.FormatTestReportArgs(
            result=api.TestResult(
                info=[
                    api.TestCaseInfo(
                        name=i["name"],
                        error=i.get("error", ""),
                        duration=int(i["duration"]),
                        log_message=i.get("log_message", ""),
                    )
                    for i in a["result"]["info"]
                ]
            )
        )
    raise ValueError(f"no args builder for rpc {rpc}")


def _call(instance, case):
    rpc = case["rpc"]
    method = {
        "KclService.Ping": instance.ping,
        "KclService.ExecProgram": instance.exec_program,
        "KclService.FormatCode": instance.format_code,
        "KclService.ValidateCode": instance.validate_code,
        "KclService.GenerateKcl": instance.generate_kcl,
        "KclService.GenerateToml": instance.generate_toml,
        "KclService.FormatTestReport": instance.format_test_report,
    }[rpc]
    return method(_build_args(case))


def _actual_fields(case, result):
    actual = {}
    for field in case["expect"]:
        value = getattr(result, field)
        if isinstance(value, (bytes, bytearray)):
            value = bytes(value).decode("utf-8")
        actual[field] = value
    return actual


def _diff(expect, actual):
    lines = []
    for field in expect:
        want, got = expect[field], actual.get(field)
        if want == got:
            continue
        lines.append(f"  field `{field}` mismatch:")
        lines.extend(
            "    " + line
            for line in difflib.unified_diff(
                str(want).splitlines(keepends=True),
                str(got).splitlines(keepends=True),
                fromfile="expected",
                tofile="actual",
            )
        )
    return "\n".join(lines)


_cases = _load_cases()

_api_instance = None
_available_methods = None


def _ensure_api():
    global _api_instance
    if _api_instance is None:
        _api_instance = api.API()
    return _api_instance


def _methods():
    global _available_methods
    if _available_methods is None:
        try:
            _available_methods = set(_ensure_api().list_method().method_name_list)
        except Exception:
            # The loaded core predates BuiltinService.ListMethod: treat the
            # RPC surface as unknown so new_core cases are skipped.
            _available_methods = set()
    return _available_methods


@pytest.mark.parametrize("case", _cases, ids=[c["name"] for c in _cases])
def test_consistency(case):
    if case["new_core"] and case["rpc"] not in _methods():
        pytest.skip(
            f"core does not list {case['rpc']} (old core); "
            "regenerate cases.json against a new core to enable"
        )
    result = _call(_ensure_api(), case)
    actual = _actual_fields(case, result)
    assert actual == case["expect"], (
        f"consistency case `{case['name']}` ({case['rpc']}) mismatch:\n"
        f"{_diff(case['expect'], actual)}"
    )
