namespace KclLib.Tests;

using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Google.Protobuf;
using KclLib.API;
using Microsoft.VisualStudio.TestTools.UnitTesting;

/// <summary>
/// Cross-language consistency runner: executes the hermetic cases from
/// tests/consistency/cases.json (generated by tests/consistency/generate_cases.py)
/// and asserts the same golden expectations as every other language runner.
///
/// Run with: dotnet test KclLib.Tests/KclLib.Tests.csproj --filter ConsistencyTest
/// </summary>
[TestClass]
// The coverage guard and the manifest cache are process-wide state, so the
// class must not be interleaved with another run of itself.
[DoNotParallelize]
public class ConsistencyTest
{
    static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };
    static readonly Lazy<(string Path, JsonDocument Doc)> Manifest = new(LoadManifest);
    static readonly Lazy<API> ApiInstance = new(() => new API());
    static readonly Lazy<HashSet<string>> AvailableMethods = new(LoadMethods);

    /// <summary>
    /// Canonical protobuf JSON -- the default dialect, so a field the core left
    /// unset is absent rather than rendered as an empty value -- with the
    /// original proto field names, so `pkg_path` stays `pkg_path`.
    /// </summary>
    static readonly JsonFormatter ProtoJson =
        new(JsonFormatter.Settings.Default.WithPreserveProtoFieldNames(true));

    /// <summary>
    /// The marker generate_cases.py writes into a path that names a template
    /// rather than a file: `scratch:a/b.k` means "b.k inside a fresh copy of
    /// testdata/a".
    /// </summary>
    const string ScratchPrefix = "scratch:";

    /// <summary>
    /// Every case this class executes, recorded at the top of <see cref="RunCase"/>
    /// rather than at the end so a case that fails is not additionally reported
    /// as unexecuted.
    /// </summary>
    static readonly HashSet<string> Executed = new();

    static string RepoRoot
    {
        get
        {
            // Tests run with the CWD somewhere under bin/<config>/<tfm>/; walk
            // up to the KclLib.Tests project directory, then two levels to the
            // repository root (mirrors APITest.FindCsprojInParentDirectory).
            var dir = new DirectoryInfo(Environment.CurrentDirectory);
            while (dir != null && dir.GetFiles("*.csproj").Length == 0)
            {
                dir = dir.Parent;
            }
            return dir?.Parent?.Parent?.FullName
                ?? throw new InvalidOperationException("could not locate repository root");
        }
    }

    static string TestData => Path.Combine(RepoRoot, "tests", "consistency", "testdata");

    static (string, JsonDocument) LoadManifest()
    {
        var path = Path.Combine(RepoRoot, "tests", "consistency", "cases.json");
        Assert.IsTrue(
            File.Exists(path),
            $"consistency manifest not found at {path}. Run `python tests/consistency/generate_cases.py` to generate it.");
        var doc = JsonDocument.Parse(File.ReadAllText(path));
        Assert.AreEqual(1, doc.RootElement.GetProperty("version").GetInt32(), "unsupported manifest version");
        return (path, doc);
    }

    /// <summary>
    /// Determine the available RPC surface once per run. Cores that predate
    /// BuiltinService.ListMethod answer with an empty list (or throw), in
    /// which case new_core cases are skipped.
    /// </summary>
    static HashSet<string> LoadMethods()
    {
        var methods = new HashSet<string>();
        try
        {
            foreach (var name in ApiInstance.Value.ListMethod().MethodNameList)
            {
                methods.Add(name);
            }
        }
        catch
        {
            // treat the RPC surface as unknown
        }
        return methods;
    }

    static JsonElement FindCase(string name)
    {
        foreach (var c in Manifest.Value.Doc.RootElement.GetProperty("cases").EnumerateArray())
        {
            if (c.GetProperty("name").GetString() == name)
            {
                return c;
            }
        }
        Assert.Fail($"consistency case not found in manifest: {name}");
        return default;
    }

    static void Skip(string reason)
    {
        // MSTest has no dynamic skip; inconclusive keeps the run green while
        // recording the skip reason in the test output.
        Assert.Inconclusive(reason);
    }

    static string Diff(string expected, string actual)
    {
        var el = expected.Split('\n');
        var al = actual.Split('\n');
        var n = Math.Max(el.Length, al.Length);
        var sb = new StringBuilder("--- expected\n+++ actual\n");
        for (var i = 0; i < n; i++)
        {
            var e = i < el.Length ? el[i] : null;
            var a = i < al.Length ? al[i] : null;
            if (e != null && e == a)
            {
                sb.Append("  ").Append(e).Append('\n');
            }
            else
            {
                if (e != null)
                {
                    sb.Append("- ").Append(e).Append('\n');
                }
                if (a != null)
                {
                    sb.Append("+ ").Append(a).Append('\n');
                }
            }
        }
        return sb.ToString();
    }

    static void AssertField(string caseName, string field, string expected, string actual)
    {
        Assert.AreEqual(
            expected,
            actual,
            $"consistency case `{caseName}` field `{field}` mismatch:\n{Diff(expected, actual)}");
    }

    /// <summary>
    /// Assert that a projection matches the pinned fields of the manifest. Only
    /// the fields the manifest pins are compared, so adding a field to `expect`
    /// is the only way to start asserting on it -- and a pinned field the
    /// projection does not produce is still a failure, because the key is
    /// missing from the trimmed object either way.
    /// </summary>
    static void AssertShape(string caseName, JsonElement expect, JsonObject actual)
    {
        var trimmed = new JsonObject();
        foreach (var field in expect.EnumerateObject())
        {
            if (actual.ContainsKey(field.Name))
            {
                trimmed[field.Name] = actual[field.Name]?.DeepClone();
            }
        }
        var want = Render(JsonNode.Parse(expect.GetRawText()));
        var got = Render(trimmed);
        Assert.AreEqual(want, got, $"consistency case `{caseName}` mismatch:\n{Diff(want, got)}");
    }

    /// <summary>
    /// Sort every object key and drop `filename`. The schema-mapping documents
    /// hold two protobuf maps whose iteration order is undefined, and `filename`
    /// is an absolute path that differs on every machine, so neither can be
    /// pinned as it arrives.
    /// </summary>
    static JsonNode? Canonical(JsonNode? node)
    {
        if (node is JsonObject obj)
        {
            var outObj = new JsonObject();
            foreach (var key in obj.Select(entry => entry.Key).OrderBy(key => key, StringComparer.Ordinal))
            {
                if (key != "filename")
                {
                    outObj[key] = Canonical(obj[key]);
                }
            }
            return outObj;
        }
        if (node is JsonArray array)
        {
            var outArray = new JsonArray();
            foreach (var item in array)
            {
                outArray.Add(Canonical(item));
            }
            return outArray;
        }
        // A node can only ever have one parent, so hand back a detached copy.
        return node?.DeepClone();
    }

    static string Render(JsonNode? node) => Canonical(node)?.ToJsonString() ?? "null";

    /// <summary>The schema-mapping documents, in the form every binding can produce.</summary>
    static JsonNode KclTypes<TValue>(IReadOnlyDictionary<string, TValue> mapping) where TValue : IMessage
    {
        var document = new JsonObject();
        foreach (var entry in mapping)
        {
            document[entry.Key] = JsonNode.Parse(ProtoJson.Format(entry.Value));
        }
        return document;
    }

    static JsonNode Text(string value) => JsonValue.Create(value);

    static JsonNode Num(long value) => JsonValue.Create(value);

    static JsonNode Bool(bool value) => JsonValue.Create(value);

    static JsonArray Strings(IEnumerable<string?> values)
    {
        var array = new JsonArray();
        foreach (var value in values)
        {
            array.Add(value is null ? null : JsonValue.Create(value));
        }
        return array;
    }

    static JsonArray Pair(string key, string value) =>
        new JsonArray(JsonValue.Create(key), JsonValue.Create(value));

    static JsonArray Pair(string key, bool value) =>
        new JsonArray(JsonValue.Create(key), JsonValue.Create(value));

    /// <summary>The manifest omits default-valued fields, so an absent field is `default`.</summary>
    static JsonElement Field(JsonElement node, string name) =>
        node.ValueKind == JsonValueKind.Object && node.TryGetProperty(name, out var value) ? value : default;

    /// <summary>The manifest omits default-valued fields, so an absent string is "".</summary>
    static string Text(JsonElement value, string fallback = "") =>
        value.ValueKind == JsonValueKind.String ? value.GetString()! : fallback;

    /// <summary>The manifest omits default-valued fields, so an absent flag is false.</summary>
    static bool Flag(JsonElement value) => value.ValueKind == JsonValueKind.True;

    static List<string> StringList(JsonElement values)
    {
        var list = new List<string>();
        if (values.ValueKind == JsonValueKind.Array)
        {
            foreach (var value in values.EnumerateArray())
            {
                list.Add(value.GetString() ?? "");
            }
        }
        return list;
    }

    /// <summary>
    /// Copy a scratch template and return the path inside the copy. Each case
    /// gets its own temporary directory, so two cases -- and two runs -- never
    /// observe each other's writes and the repository is never the target of an
    /// RPC that rewrites files.
    /// </summary>
    static string Scratch(string rest)
    {
        var slash = rest.IndexOf('/');
        var template = slash < 0 ? rest : rest[..slash];
        var tail = slash < 0 ? "" : rest[(slash + 1)..];
        var src = Path.Combine(TestData, template);
        Assert.IsTrue(Directory.Exists(src), $"scratch template is not a directory: {src}");
        var dest = Path.Combine(
            Path.Combine(Path.GetTempPath(), $"kcl-consistency-{Guid.NewGuid():N}"),
            template);
        CopyTree(src, dest);
        return tail.Length == 0 ? dest : Path.Combine(dest, tail);
    }

    static void CopyTree(string src, string dest)
    {
        Directory.CreateDirectory(dest);
        foreach (var dir in Directory.EnumerateDirectories(src, "*", SearchOption.AllDirectories))
        {
            Directory.CreateDirectory(Path.Combine(dest, Path.GetRelativePath(src, dir)));
        }
        foreach (var file in Directory.EnumerateFiles(src, "*", SearchOption.AllDirectories))
        {
            File.Copy(file, Path.Combine(dest, Path.GetRelativePath(src, file)), overwrite: true);
        }
    }

    /// <summary>
    /// Manifest path entries are repo-relative (pinned by generate_cases.py);
    /// absolute entries are kept as-is.
    /// </summary>
    static string ResolvePath(string path)
    {
        if (path.StartsWith(ScratchPrefix, StringComparison.Ordinal))
        {
            return Scratch(path[ScratchPrefix.Length..]);
        }
        return Path.IsPathRooted(path) ? path : Path.Combine(RepoRoot, path);
    }

    static List<string> ResolvePaths(JsonElement values) =>
        StringList(values).Select(ResolvePath).ToList();

    /// <summary>
    /// Build <see cref="ExecProgramArgs"/> from the manifest. `k_filename_list`
    /// is resolved by the core against the process working directory rather
    /// than against `work_dir`, so it has to be made absolute here or it will
    /// not survive being run from another directory.
    /// </summary>
    static ExecProgramArgs ExecArgs(JsonElement a)
    {
        var execArgs = new ExecProgramArgs();
        foreach (var code in StringList(Field(a, "k_code_list")))
        {
            execArgs.KCodeList.Add(code);
        }
        var workDir = ResolvePath(Text(Field(a, "work_dir"), "."));
        foreach (var name in StringList(Field(a, "k_filename_list")))
        {
            execArgs.KFilenameList.Add(
                Path.IsPathRooted(name) ? name : Path.Combine(workDir, name));
        }
        if (Field(a, "work_dir").ValueKind == JsonValueKind.String)
        {
            execArgs.WorkDir = workDir;
        }
        if (Field(a, "args").ValueKind == JsonValueKind.Array)
        {
            foreach (var arg in Field(a, "args").EnumerateArray())
            {
                execArgs.Args.Add(new Argument
                {
                    Name = Text(Field(arg, "name")),
                    Value = Text(Field(arg, "value")),
                });
            }
        }
        foreach (var over in StringList(Field(a, "overrides")))
        {
            execArgs.Overrides.Add(over);
        }
        return execArgs;
    }

    /// <summary>
    /// Build <see cref="ParseProgramArgs"/> from the manifest. Path entries are
    /// pinned repo-relative by generate_cases.py; they are resolved against the
    /// repository root (the parent of the directory holding cases.json), while
    /// absolute entries are kept as-is.
    /// </summary>
    static ParseProgramArgs ParseArgs(JsonElement node)
    {
        var parseArgs = new ParseProgramArgs();
        foreach (var path in ResolvePaths(Field(node, "paths")))
        {
            parseArgs.Paths.Add(path);
        }
        foreach (var source in StringList(Field(node, "sources")))
        {
            parseArgs.Sources.Add(source);
        }
        return parseArgs;
    }

    static void RunCase(string name)
    {
        lock (Executed)
        {
            Executed.Add(name);
        }
        var c = FindCase(name);
        var rpc = c.GetProperty("rpc").GetString()!;
        var newCore = c.GetProperty("new_core").GetBoolean();
        var args = c.GetProperty("args");
        var expect = c.GetProperty("expect");

        switch (rpc)
        {
            case "KclService.Ping":
            {
                var result = ApiInstance.Value.Ping(new PingArgs { Value = args.GetProperty("value").GetString() });
                AssertField(name, "value", expect.GetProperty("value").GetString()!, result.Value);
                break;
            }
            case "KclService.ExecProgram":
            {
                var result = ApiInstance.Value.ExecProgram(ExecArgs(args));
                if (expect.TryGetProperty("yaml_result", out var yaml))
                {
                    AssertField(name, "yaml_result", yaml.GetString()!, result.YamlResult);
                }
                if (expect.TryGetProperty("json_result", out var json))
                {
                    AssertField(name, "json_result", json.GetString()!, result.JsonResult);
                }
                break;
            }
            case "KclService.FormatCode":
            {
                var result = ApiInstance.Value.FormatCode(new FormatCodeArgs { Source = args.GetProperty("source").GetString() });
                AssertField(name, "formatted", expect.GetProperty("formatted").GetString()!, result.Formatted.ToStringUtf8());
                break;
            }
            case "KclService.ValidateCode":
            {
                var result = ApiInstance.Value.ValidateCode(new ValidateCodeArgs
                {
                    Code = args.GetProperty("code").GetString(),
                    Data = args.GetProperty("data").GetString(),
                    Format = Text(Field(args, "format")),
                });
                var actual = new JsonObject
                {
                    ["success"] = Bool(result.Success),
                    // The diagnostic carries ANSI colour escapes, a random temp
                    // path and a temp filename, so the string itself is not
                    // pinnable but its presence is.
                    ["has_error_message"] = Bool(result.ErrMessage.Length > 0),
                };
                if (expect.TryGetProperty("err_message", out _))
                {
                    actual["err_message"] = Text(result.ErrMessage);
                }
                AssertShape(name, expect, actual);
                break;
            }
            case "KclService.ParseFile":
            {
                var result = ApiInstance.Value.ParseFile(new ParseFileArgs
                {
                    Path = Text(Field(args, "path")),
                    Source = Text(Field(args, "source")),
                });
                // A bare `Module` document, so the statements are at `body`.
                var module = result.AstJson.Length == 0 ? null : JsonNode.Parse(result.AstJson);
                AssertShape(name, expect, new JsonObject
                {
                    ["body_count"] = Num((module?["body"] as JsonArray)?.Count ?? 0),
                    ["error_count"] = Num(result.Errors.Count),
                    ["deps"] = Strings(result.Deps),
                });
                break;
            }
            case "KclService.ParseProgram":
            {
                var result = ApiInstance.Value.ParseProgram(ParseArgs(args));
                // `ParseProgram` returns a `pkgs` document, not a module: one
                // Module per file, keyed by package path.
                var doc = result.AstJson.Length == 0 ? null : JsonNode.Parse(result.AstJson);
                var modules = (doc?["pkgs"] as JsonObject)?["__main__"] as JsonArray;
                AssertShape(name, expect, new JsonObject
                {
                    ["module_count"] = Num(modules?.Count ?? 0),
                    ["error_count"] = Num(result.Errors.Count),
                    ["paths"] = Strings(result.Paths.Select(path => Path.GetFileName(path))),
                });
                break;
            }
            case "KclService.ListOptions":
            {
                var result = ApiInstance.Value.ListOptions(ParseArgs(args));
                var options = result.Options
                    .OrderBy(option => option.Name, StringComparer.Ordinal)
                    .Select(option => Pair(option.Name, option.Required));
                AssertShape(name, expect, new JsonObject
                {
                    ["option_count"] = Num(result.Options.Count),
                    ["options"] = new JsonArray(options.ToArray<JsonNode?>()),
                });
                break;
            }
            case "KclService.ListVariables":
            {
                var listArgs = new ListVariablesArgs
                {
                    Options = new ListVariablesOptions
                    {
                        MergeProgram = Flag(Field(Field(args, "options"), "merge_program")),
                    },
                };
                foreach (var file in ResolvePaths(Field(args, "files")))
                {
                    listArgs.Files.Add(file);
                }
                foreach (var spec in StringList(Field(args, "specs")))
                {
                    listArgs.Specs.Add(spec);
                }
                var result = ApiInstance.Value.ListVariables(listArgs);
                var values = new JsonObject();
                foreach (var spec in result.Variables.OrderBy(spec => spec.Key, StringComparer.Ordinal))
                {
                    values[spec.Key] = Strings(spec.Value.Variables.Select(variable => variable.Value));
                }
                AssertShape(name, expect, new JsonObject
                {
                    ["values"] = values,
                    ["unsupported_codes"] = Strings(result.UnsupportedCodes),
                    ["parse_error_count"] = Num(result.ParseErrors.Count),
                });
                break;
            }
            case "KclService.LoadPackage":
            {
                var result = ApiInstance.Value.LoadPackage(new LoadPackageArgs
                {
                    ParseArgs = ParseArgs(Field(args, "parse_args")),
                    ResolveAst = Flag(Field(args, "resolve_ast")),
                    LoadBuiltin = Flag(Field(args, "load_builtin")),
                    WithAstIndex = Flag(Field(args, "with_ast_index")),
                });
                AssertShape(name, expect, new JsonObject
                {
                    ["path_count"] = Num(result.Paths.Count),
                    ["type_error_count"] = Num(result.TypeErrors.Count),
                    ["parse_error_count"] = Num(result.ParseErrors.Count),
                    ["symbol_count"] = Num(result.Symbols.Count),
                    ["scope_count"] = Num(result.Scopes.Count),
                    ["has_kcl_mod"] = Bool(result.KclMod is not null),
                    ["kcl_mod_name"] = Text(result.KclMod?.Package?.Name ?? ""),
                    ["app_count"] = Num(result.Apps.Count),
                    ["import_count"] = Num(result.Imports.Count),
                });
                break;
            }
            case "KclService.GetSchemaTypeMapping":
            case "KclService.GetSchemaTypeMappingUnderPath":
            {
                var mappingArgs = new GetSchemaTypeMappingArgs
                {
                    ExecArgs = ExecArgs(Field(args, "exec_args")),
                    SchemaName = Text(Field(args, "schema_name")),
                };
                var mapping = rpc == "KclService.GetSchemaTypeMapping"
                    ? KclTypes(ApiInstance.Value.GetSchemaTypeMapping(mappingArgs).SchemaTypeMapping)
                    : KclTypes(ApiInstance.Value.GetSchemaTypeMappingUnderPath(mappingArgs).SchemaTypeMapping);
                AssertShape(name, expect, new JsonObject { ["type_mapping"] = mapping });
                break;
            }
            case "KclService.GetVersion":
            {
                var result = ApiInstance.Value.GetVersion(new GetVersionArgs());
                var parts = result.Version.Split('.');
                AssertShape(name, expect, new JsonObject
                {
                    ["version"] = Text(parts.Length >= 2 ? $"{parts[0]}.{parts[1]}" : result.Version),
                    ["has_checksum"] = Bool(result.Checksum.Length > 0),
                    ["has_git_sha"] = Bool(result.GitSha.Length > 0),
                    ["has_version_info"] = Bool(result.VersionInfo.Length > 0),
                });
                break;
            }
            case "BuiltinService.ListMethod":
            {
                var names = ApiInstance.Value.ListMethod().MethodNameList;
                AssertShape(name, expect, new JsonObject
                {
                    ["has_kclservice_ping"] = Bool(names.Contains("KclService.Ping")),
                    ["has_kclservice_parse_program"] = Bool(names.Contains("KclService.ParseProgram")),
                    ["has_builtinservice_list_method"] = Bool(names.Contains("BuiltinService.ListMethod")),
                    ["method_count"] = Num(names.Count),
                    ["has_empty_name"] = Bool(names.Any(string.IsNullOrEmpty)),
                });
                break;
            }
            case "KclService.LintPath":
            {
                var lintArgs = new LintPathArgs();
                foreach (var path in ResolvePaths(Field(args, "paths")))
                {
                    lintArgs.Paths.Add(path);
                }
                var result = ApiInstance.Value.LintPath(lintArgs);
                AssertShape(name, expect, new JsonObject
                {
                    ["result_count"] = Num(result.Results.Count),
                    ["has_result"] = Bool(result.Results.Count > 0),
                });
                break;
            }
            case "KclService.FormatPath":
            {
                var result = ApiInstance.Value.FormatPath(new FormatPathArgs
                {
                    Path = ResolvePath(Text(Field(args, "path"))),
                    DryRun = Flag(Field(args, "dry_run")),
                });
                AssertShape(name, expect, new JsonObject
                {
                    ["changed_count"] = Num(result.ChangedPaths.Count),
                    ["changed"] = Strings(
                        result.ChangedPaths
                            .Select(path => Path.GetFileName(path))
                            .OrderBy(name => name, StringComparer.Ordinal)),
                });
                break;
            }
            case "KclService.Test":
            {
                var testArgs = new TestArgs
                {
                    ExecArgs = ExecArgs(Field(args, "exec_args")),
                    RunRegexp = Text(Field(args, "run_regexp")),
                    FailFast = Flag(Field(args, "fail_fast")),
                    Coverage = Flag(Field(args, "coverage")),
                };
                foreach (var pkg in ResolvePaths(Field(args, "pkg_list")))
                {
                    testArgs.PkgList.Add(pkg);
                }
                var result = ApiInstance.Value.Test(testArgs);
                AssertShape(name, expect, new JsonObject
                {
                    ["names"] = Strings(
                        result.Info.Select(info => info.Name).OrderBy(name => name, StringComparer.Ordinal)),
                    ["failed"] = Strings(
                        result.Info
                            .Where(info => info.Error.Length > 0)
                            .Select(info => info.Name)
                            .OrderBy(name => name, StringComparer.Ordinal)),
                });
                break;
            }
            case "KclService.OverrideFile":
            {
                var overrideArgs = new OverrideFileArgs { File = ResolvePath(Text(Field(args, "file"))) };
                foreach (var spec in StringList(Field(args, "specs")))
                {
                    overrideArgs.Specs.Add(spec);
                }
                foreach (var path in ResolvePaths(Field(args, "import_paths")))
                {
                    overrideArgs.ImportPaths.Add(path);
                }
                var result = ApiInstance.Value.OverrideFile(overrideArgs);
                AssertShape(name, expect, new JsonObject
                {
                    ["result"] = Bool(result.Result),
                    ["parse_error_count"] = Num(result.ParseErrors.Count),
                });
                break;
            }
            case "KclService.LoadSettingsFiles":
            {
                var settingsArgs = new LoadSettingsFilesArgs
                {
                    WorkDir = ResolvePath(Text(Field(args, "work_dir"))),
                };
                foreach (var file in ResolvePaths(Field(args, "files")))
                {
                    settingsArgs.Files.Add(file);
                }
                var result = ApiInstance.Value.LoadSettingsFiles(settingsArgs);
                AssertShape(name, expect, new JsonObject
                {
                    // A protobuf repeated field's iteration order is undefined,
                    // and the manifest pins these as a set.
                    ["options"] = new JsonArray(result.KclOptions
                        .OrderBy(option => option.Key, StringComparer.Ordinal)
                        .Select(option => Pair(option.Key, option.Value))
                        .ToArray<JsonNode?>()),
                    ["output"] = Text(result.KclCliConfigs.Output),
                    ["overrides"] = Strings(result.KclCliConfigs.Overrides),
                    ["strict_range_check"] = Bool(result.KclCliConfigs.StrictRangeCheck),
                    ["verbose"] = Num(result.KclCliConfigs.Verbose),
                });
                break;
            }
            case "KclService.UpdateDependencies":
            {
                var result = ApiInstance.Value.UpdateDependencies(new UpdateDependenciesArgs
                {
                    ManifestPath = ResolvePath(Text(Field(args, "manifest_path"))),
                    Vendor = Flag(Field(args, "vendor")),
                });
                AssertShape(name, expect, new JsonObject
                {
                    ["external_pkg_count"] = Num(result.ExternalPkgs.Count),
                });
                break;
            }
            case "KclService.FormatTestReport":
            {
                if (newCore && !AvailableMethods.Value.Contains(rpc))
                {
                    Skip($"core does not list {rpc} (old core)");
                }
                var reportArgs = new FormatTestReportArgs { Result = new KclLib.API.TestResult() };
                foreach (var info in args.GetProperty("result").GetProperty("info").EnumerateArray())
                {
                    reportArgs.Result.Info.Add(new TestCaseInfo
                    {
                        Name = info.GetProperty("name").GetString(),
                        Error = info.TryGetProperty("error", out var e) ? e.GetString() : "",
                        // uint64 values are canonical proto JSON strings in the manifest.
                        Duration = ulong.Parse(info.GetProperty("duration").GetString()!),
                        LogMessage = info.TryGetProperty("log_message", out var l) ? l.GetString() : "",
                    });
                }
                var result = ApiInstance.Value.FormatTestReport(reportArgs);
                AssertField(name, "report", expect.GetProperty("report").GetString()!, result.Report);
                break;
            }
            case "KclService.GenerateToml":
            {
                if (newCore && !AvailableMethods.Value.Contains(rpc))
                {
                    Skip($"core does not list {rpc} (old core)");
                }
                var result = ApiInstance.Value.GenerateToml(new GenerateTomlArgs
                {
                    ExecArgs = ExecArgs(Field(args, "exec_args")),
                    SortKeys = Flag(Field(args, "sort_keys")),
                });
                AssertField(name, "toml", expect.GetProperty("toml").GetString()!, result.Toml);
                break;
            }
            case "KclService.GenerateKcl":
            {
                if (newCore && !AvailableMethods.Value.Contains(rpc))
                {
                    Skip($"core does not list {rpc} (old core)");
                }
                var result = ApiInstance.Value.GenerateKcl(new GenerateKclArgs
                {
                    Source = args.GetProperty("source").GetString(),
                    Filename = args.GetProperty("filename").GetString(),
                    Format = args.TryGetProperty("format", out var fmt) ? fmt.GetString() : "",
                });
                AssertField(name, "kcl", expect.GetProperty("kcl").GetString()!, result.Kcl);
                break;
            }
            case "KclService.GenerateOpenAPI":
            {
                if (newCore && !AvailableMethods.Value.Contains(rpc))
                {
                    Skip($"core does not list {rpc} (old core)");
                }
                var result = ApiInstance.Value.GenerateOpenAPI(new GenerateOpenAPIArgs
                {
                    ParseArgs = ParseArgs(args.GetProperty("parse_args")),
                    Version = args.TryGetProperty("version", out var v) ? v.GetString() : "",
                });
                AssertField(name, "spec", expect.GetProperty("spec").GetString()!, result.Spec);
                break;
            }
            case "KclService.GenerateProto":
            {
                if (newCore && !AvailableMethods.Value.Contains(rpc))
                {
                    Skip($"core does not list {rpc} (old core)");
                }
                var result = ApiInstance.Value.GenerateProto(new GenerateProtoArgs
                {
                    ParseArgs = ParseArgs(args.GetProperty("parse_args")),
                    Package = args.TryGetProperty("package", out var p) ? p.GetString() : "",
                });
                AssertField(name, "proto", expect.GetProperty("proto").GetString()!, result.Proto);
                break;
            }
            case "KclService.GenerateDoc":
            {
                if (newCore && !AvailableMethods.Value.Contains(rpc))
                {
                    Skip($"core does not list {rpc} (old core)");
                }
                var result = ApiInstance.Value.GenerateDoc(new GenerateDocArgs
                {
                    ParseArgs = ParseArgs(args.GetProperty("parse_args")),
                    Format = args.TryGetProperty("format", out var f) ? f.GetString() : "",
                });
                AssertField(name, "content", expect.GetProperty("content").GetString()!, result.Content);
                break;
            }
            default:
                Assert.Fail($"no runner support for rpc {rpc}");
                break;
        }
    }

    /// <summary>
    /// Every case in the manifest must be dispatched by a [TestMethod] in this
    /// class. Without this, a runner that covers half the spec passes silently
    /// -- which is exactly how this class went from 13 cases to 29 in the
    /// manifest while still only running 13.
    ///
    /// A [ClassCleanup] rather than a [TestMethod] because MSTest does not order
    /// methods: run it as a test and it would report a half-covered manifest as
    /// a failure on a green run.
    /// </summary>
    [ClassCleanup]
    public static void EveryManifestCaseHasARunner()
    {
        var missing = new List<string>();
        foreach (var c in Manifest.Value.Doc.RootElement.GetProperty("cases").EnumerateArray())
        {
            var caseName = c.GetProperty("name").GetString()!;
            lock (Executed)
            {
                if (!Executed.Contains(caseName))
                {
                    missing.Add(caseName);
                }
            }
        }
        Assert.AreEqual(
            "",
            string.Join(", ", missing),
            "cases.json has cases this runner does not execute; add a test method for each");
    }

    [TestMethod]
    public void TestPing() => RunCase("ping");

    [TestMethod]
    public void TestExecProgramBasic() => RunCase("exec_program_basic");

    [TestMethod]
    public void TestExecProgramOverrides() => RunCase("exec_program_overrides");

    [TestMethod]
    public void TestFormatCode() => RunCase("format_code");

    [TestMethod]
    public void TestValidateCodeOk() => RunCase("validate_code_ok");

    [TestMethod]
    public void TestValidateCodeInvalid() => RunCase("validate_code_invalid");

    [TestMethod]
    public void TestGenerateKclJson() => RunCase("generate_kcl_json");

    [TestMethod]
    public void TestGenerateKclYaml() => RunCase("generate_kcl_yaml");

    [TestMethod]
    public void TestGenerateToml() => RunCase("generate_toml");

    [TestMethod]
    public void TestFormatTestReport() => RunCase("format_test_report");

    [TestMethod]
    public void TestGenerateOpenAPIV3() => RunCase("generate_openapi_v3");

    [TestMethod]
    public void TestGenerateProto() => RunCase("generate_proto");

    [TestMethod]
    public void TestGenerateDocMd() => RunCase("generate_doc_md");

    [TestMethod]
    public void TestParseFile() => RunCase("parse_file");

    [TestMethod]
    public void TestParseProgram() => RunCase("parse_program");

    [TestMethod]
    public void TestListOptions() => RunCase("list_options");

    [TestMethod]
    public void TestListVariables() => RunCase("list_variables");

    [TestMethod]
    public void TestLoadPackage() => RunCase("load_package");

    [TestMethod]
    public void TestGetSchemaTypeMapping() => RunCase("get_schema_type_mapping");

    [TestMethod]
    public void TestGetSchemaTypeMappingUnderPath() => RunCase("get_schema_type_mapping_under_path");

    [TestMethod]
    public void TestGetVersion() => RunCase("get_version");

    [TestMethod]
    public void TestListMethod() => RunCase("list_method");

    [TestMethod]
    public void TestLintPathClean() => RunCase("lint_path_clean");

    [TestMethod]
    public void TestLintPathWithErrors() => RunCase("lint_path_with_errors");

    [TestMethod]
    public void TestFormatPathDryRun() => RunCase("format_path_dry_run");

    [TestMethod]
    public void TestTestRun() => RunCase("test_run");

    [TestMethod]
    public void TestOverrideFile() => RunCase("override_file");

    [TestMethod]
    public void TestLoadSettingsFiles() => RunCase("load_settings_files");

    [TestMethod]
    public void TestUpdateDependenciesNoDeps() => RunCase("update_dependencies_no_deps");
}